### ISSUE TITLE
Mods I will be adding:

### ISSUE THREAD

**Issue by BBoldt** [BBoldt/Unabridged#189]
* Thermal Dynamics --- Thermal Expansion's conduit system
* Resourceful Crops --- More balanced, less junk magical crops replacement
* Thermal Smeltery --- http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2352947-thermal-smeltery
* Integrated Circuits ---  http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2352247-integrated-circuits-alpha-v0-8r23
* Pistrionics 2 --- http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1294844-pistronics-modular-pistons-rotators-and-statues-1

**Comment by dylanpiera** [comment]
maybe ae2techaddon
if ever updated..
