### ISSUE TITLE
ops can't join server

### ISSUE THREAD

**Issue by Fuhrmaaj** [BBoldt/Unabridged#205]
I'm not sure if this is just me, but I have to de-op players before they can join the server. I can op them once they're in and they can play normally. I don't know anything else about this one, sorry.

**Comment by samgaud** [comment]
Same problem here.. If I op someone he instantly log out if he try to log later.. I'll get you a crash report or something when I get home.

**Comment by BBoldt** [comment]
@samgaud 

The problem seems to be something to do with OPIS, if you remove that mod serverside I don't think the problem will exist.

Another alternative is to deop yourself before joining the server.

I will be looking into this more.

**Comment by BBoldt** [comment]
Found some info about this problem. I will probably be able to fix it in the next version.

https://github.com/MCServerTools/ServerTools-CORE/issues/11

It's an issue between opis and servertools.

**Comment by BBoldt** [comment]
"As a temporary workaround you can set Color OP Messages to false in the servertools/core.cfg file."

**Comment by BBoldt** [comment]
Fixed in next version.
