### ISSUE TITLE
Can't craft PneumaticCraft Charging Station

### ISSUE THREAD

**Issue by Fuhrmaaj** [BBoldt/Unabridged#220]
The Charging Station is crafted from Fire Flower Seed plastic. The only crafting recipe for Fire Flower Seeds is from 2 Biomes O' Plenty Burning Blossoms which only spawn in Undergardens. Well they're not generating in any of the 12 Undergardens I checked and bonemeal doesn't draw them out. The picture on the BoP wiki indicates that they grow on Netherrack but I haven't had any success finding them.

If you need to fly over the Nether to find a random flower, then you can't get into PneumaticCraft until you're very well equipped. This bars PC from anybody who doesn't get lucky in the early game. Biomes O' Plenty stuff is probably not the best thing to use for the recipe because it doesn't spawn consistently. The Charging Station is necessary in order to make the PC Pneumatic Wrench work and effectively bars players from starting it until this flower can be found.

Suggest changing the recipe to use blaze powder instead of anything from BoP.

**Comment by BBoldt** [comment]
I'm gonna make all the Pneumaticraft seed recipes use dyes like Crash Landing.

**Comment by BBoldt** [comment]
Fixed in next version
