### ISSUE TITLE
Missing particles

### ISSUE THREAD

**Issue by samgaud** [BBoldt/Unabridged#221]
Every breaking object particles (not the hitting particle, the kinda pop like particle at the end) missing as well as explosion animation. Tried delete-install instance change nothing. Also It's the same in ssp and smp so maybe client related?

**Comment by BBoldt** [comment]
I've noticed heart particles are missing when breeding animals as well.

I suspect it might be the sprinkles_for_vanilla mod acting weird. Will look into it.

**Comment by BBoldt** [comment]
Should be fixed in next version.
