### ISSUE TITLE
Mobs are destroying warded blocks and cursed earth

### ISSUE THREAD

**Issue by Fuhrmaaj** [BBoldt/Unabridged#225]
Since the last update, my cursed earth mob farm under my blood altar keeps getting destroyed. I haven't seen what happens but I heard something strange before I saw a hole get ripped through blocks I had warded with Thaumcraft. I think the sound was one of the strange weapons that the QuiverMobs use, but I'm not sure how best to test it.

It is not meant to be possible for creepers to blow up cursed earth and it's not meant for any mob to destroy warded blocks so it's most likely being caused by a mob added by a mod.

**Comment by BBoldt** [comment]
I've noticed that the quivermob skeletons have been shooting at the other mobs lately. It's likely one of them.

I'll try to get this taken care of. If you're playing single player, just remove quivermob temporarily.

**Comment by BBoldt** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292078-quiverbow-ranged-weaponry-thought-up-by-steve?comment=600

**Comment by BBoldt** [comment]
Should be fixed in next version.

**Comment by BBoldt** [comment]
Having a problem updating to new quiverbow/quivermob.

Some sort of crash bug with hardcore ender expansion.

**Comment by Fuhrmaaj** [comment]
It's also pretty annoying that they burn down forests and shoot holes in the sides of buildings even when mob griefing is set to off (which it has been while creeper collateral is on the mend). I don't know if the mod author can figure out how to make the mob griefing rule applies to his mobs, but that would be might nice if he could.

**Comment by BBoldt** [comment]
Mob griefing isn't set to off, only creeper griefing is.

**Comment by BBoldt** [comment]
Fixed in next version. Was waiting for the guy to patch it.
