### ISSUE TITLE
Golden Chipset Costs 16 Gold

### ISSUE THREAD

**Issue by Fuhrmaaj** [BBoldt/Unabridged#227]
Before the last update, the Golden Chipset costed 1 redstone and 1 gold ingot, which is the same as it's always been. Now it costs 1 redstone, 16 gold for one chipset. The other chipsets are unchanged (Iron Chipset costs 1 redstone, 1 iron and the Diamond Chipset costs 1 redstone, 1 diamond for example). I doubt the mod author intended to change the recipe.

**Comment by BBoldt** [comment]
Fixed in next version.
