### ISSUE TITLE
Using "/help 2" crashes client

### ISSUE THREAD

**Issue by MechaJ** [BBoldt/Unabridged#230]
Using "/help 2" crashes client

**Comment by BBoldt** [comment]
I need to know what optional mods you have installed, I can't reproduce.

Also, crashlog if you got it.

**Comment by BBoldt** [comment]
As far as I'm aware though, the /help command is just broken from mods misusing it. It's difficult to narrow it down. There is a "help fix" mod, but it doesn't seem to help.

**Comment by MechaJ** [comment]
Optional mods are: Eria IRC, Inventory Tweaks, Default Key Config.

crashlog:
http://pastebin.com/bwR3gcEZ

**Comment by MechaJ** [comment]
Disabling Eria IRC solved issue

**Comment by BBoldt** [comment]
Interesting.

I'll try to get this resolved.

**Comment by BBoldt** [comment]
/help seems to be working again in very recent test versions.

Test this again after Beta 3.9 is out.
