### ISSUE TITLE
[3.8 Beta] IC2 items no longer have proper names

### ISSUE THREAD

**Issue by MechaJ** [BBoldt/Unabridged#231]
![2015-02-08_02 04 51](https://cloud.githubusercontent.com/assets/8594580/6095859/6bee191a-af37-11e4-9ee1-54025a6b4030.png)

Name localization not working for IndustrialCraft 2 after update.

**Comment by BBoldt** [comment]
http://bt.industrial-craft.net/view.php?id=1530

MFR broke IC2's localization somehow, they are working on fixing it from the IC2 side.

**Comment by BBoldt** [comment]
Will be fixed in Beta 3.9.
