### ISSUE TITLE
NEI cheat mode crash

### ISSUE THREAD

**Issue by dylanpiera** [BBoldt/Unabridged#232]
If your inventory is full and you cheat something in you crash,

Not a big problem just felt like telling!

Edit: Sorry i forgot: http://pastebin.com/ZJLh8EK5

**Comment by dylanpiera** [comment]
log posted above

**Comment by BBoldt** [comment]
https://github.com/Chicken-Bones/NotEnoughItems/issues/153

**Comment by DTV96Calibre** [comment]
This bug seems to be present in NotEnoughItems 1.0.5.118-universal for MC 1.7.10
Like the OP, for me this isn't a big deal. However, it is still a bug that I spent an hour troubleshooting because I thought it was something else.
