### ISSUE TITLE
AE 2 charger not working

### ISSUE THREAD

**Issue by dylanpiera** [BBoldt/Unabridged#233]
Im for the first time using the wooden crank to power the charger but it ain't working.
It says it has a full capacity of power and its not draining:
http://imgur.com/45ITA0K

Edit: Still not working when connecting it to a creative energy cell, Probably bug with ae2

**Comment by BBoldt** [comment]
It's working perfectly for me.

Tested on both a singleplayer and a server environment.

**Comment by dylanpiera** [comment]
When i get home il try to do it without my self added mods
else some mod i added is screwing it up

**Comment by dylanpiera** [comment]
I don't know why but today it started working again. I probably did something wrong
