### ISSUE TITLE
Extra Trees Fence Gates make Thaumcraft too hard

### ISSUE THREAD

**Issue by Fuhrmaaj** [BBoldt/Unabridged#236]
Extra Tress adds new Fence Gates for each wood type, and overwrite the default Fence Gate to be called an Oak Gate. The problem is that the Oak Gate does not have the Iter aspect, which is typically found most cheaply in Fence Gates. It is fairly important that Iter can be gotten from Fence Gates, which means there needs to be a fairly easy way to craft them.

I would like to see either the Oak Gate removed (so the Fence Gate becomes default), or Iter to be added to all Extra Trees Fence Gates (all those Iter Research Points). I imagine it's possible to craft gates from two types of wood in order to get the default Fence Gate, but this seems unnecessarily difficult.

**Comment by dylanpiera** [comment]
Haven't started thaumcraft yet, But i agree with this

**Comment by BBoldt** [comment]
https://bitbucket.org/binnie567/binnie-mods/issue/184/extra-trees-oak-gate-overwrites-vanilla

**Comment by BBoldt** [comment]
Added shapeless recipe from binnie gate to minecraft gate in the meantime, it's easier in that direction.
