### ISSUE TITLE
Remote IO Intelligent Workbench doesn't cooperate with shift-clicking

### ISSUE THREAD

**Issue by Fuhrmaaj** [BBoldt/Unabridged#237]
One of the best unique functions of the Intelligent Workbench from Remote IO is that it allows the player to choose the product of their crafting operation in the instance that two items share the same recipe. When crafting vanilla Fence Gates (whose recipe conflicts with Oak Gates from Extra Trees), after setting up the recipe to craft multiple gates, clicking the arrow to choose Fence Gate and trying to shift-click them all out, only one is crafted. Then the recipe changes to Oak Gates and the first recipe is Fence Gates, so the arrow must be clicked back to the first recipe. But shift-clicking again crafts one and swaps the recipes again.

Sorry if that sounds incredibly convoluted, but it's confusing when it happens and hard to explain. I only tested it for Oak Gates, but I imagine it's the same for any gate from Extra Trees. I don't know of any other recipe conflicts to be able to test for other recipes.

**Comment by BBoldt** [comment]
Closing this issue as it's not too severe and doesn't really effect the pack.
