### ISSUE TITLE
[3.8 Beta] Twilight Forest biomes in overworld

### ISSUE THREAD

**Issue by MechaJ** [BBoldt/Unabridged#238]
![2015-02-11_05 27 02](https://cloud.githubusercontent.com/assets/8594580/6146326/1b736e28-b1b1-11e4-8c79-001944918d65.png)
![2015-02-11_05 27 51](https://cloud.githubusercontent.com/assets/8594580/6146327/1cd47b90-b1b1-11e4-9f38-52ea7be1957a.png)

**Comment by BBoldt** [comment]
I swear, TF biomes aren't conflicting with anything, i've triple checked. There must be some sort of bug forcing them to spawn in the overworld. 

Last time this issue arose, I moved all the TF biomes to a completely different empty spot in the biome ids.

https://github.com/BBoldt/Unabridged/issues/209

I'll check again.

**Comment by MechaJ** [comment]
Okay, I have a suggestion.  https://github.com/Glitchfiend/BiomesOPlenty/issues/347
The +128 sub-biome ID problem seems confirmed in my case by the fireswamp in overworld being adjacent to an Outback biome, so if all the IDs in every other 128 block of IDs were vacated, that conceivably might fix it.

**Comment by BBoldt** [comment]
Thanks for the heads up on that issue, I will shuffle the ids around and do some more testing.

When I change ids, biomes that were previously TF will become plains.

**Comment by BBoldt** [comment]
@MechaJ I can't just vacate every other 128 block of IDs, there are only 256 all together, and there are more than 128 biomes in this pack. 

I think I might be able to use this bug to my advantage though, I can force certain biomes into sub biome slots.

I talked to a modder about this issue, and it isn't something that can be easily fixed. I understand the issue completely now though, I'll be working on a solution that at least prevents TF biomes from spawning in the overworld.

**Comment by BBoldt** [comment]
I've reshuffled the ids to places where this shouldn't be an issue anymore.

**Comment by BBoldt** [comment]
Fixed in b3.9.
