### ISSUE TITLE
Larger Pressure Pipes' tanks

### ISSUE THREAD

**Issue by BBoldt** [BBoldt/Unabridged#239]
https://github.com/bdew/pressure/issues/31

**Comment by Fuhrmaaj** [comment]
STALKER

**Comment by BBoldt** [comment]
shhhh

**Comment by Fuhrmaaj** [comment]
In config > PressurePipes, make a new file called custom.cfg (name doesn't matter). I went with 200 just to give room to go nuts. I used over 100 for my tanks, so I just picked a large number so I wouldn't have to worry about it.

```
cfg Modules {
	cfg TankBlock {
		Capacity = 32000 //Capacity of Tank Blocks in mB here
	}
}

cfg Machines {
	cfg TankController {
		cfg Modules {
			TankBlock = 200 //Maximum number of storage blocks here
		}
	}
}

**Comment by BBoldt** [comment]
Added in b3.9.
