### ISSUE TITLE
Add aspects for PMP plants

### ISSUE THREAD

**Issue by BBoldt** [BBoldt/Unabridged#240]
If it's not too difficult.

**Comment by dylanpiera** [comment]
What could go wrong..

**Comment by BBoldt** [comment]
nothing

**Comment by BBoldt** [comment]
It's too difficult.

**Comment by BBoldt** [comment]
I CAN DO THIS, I BELIEVE IN MYSELF

**Comment by dylanpiera** [comment]
Oh god.. Run.

**Comment by BBoldt** [comment]
I actually did it.

I added aspects for ALL of plant mega pack and biomes o plenty. I also added some aspects for the worldgen blocks of chisel and botania.

**Comment by dylanpiera** [comment]
I hope your not planning to add EE soon ^_^

**Comment by BBoldt** [comment]
hell no
