### ISSUE TITLE
Messy Minetweaker Scripts

### ISSUE THREAD

**Issue by Fuhrmaaj** [BBoldt/Unabridged#241]
I was just poking through the Minetweaker 3 scripts folder and I noticed a bunch of oddities. It might be worth looking over yourself, but here are a few things I caught:

archimedes.zs; excarts.zs; vanilla.zs
- somehow has no discernible formatting, I don't know how it even runs

dimstorage.zs
- this mod was removed, but a script still exists client-side

mekanism.zs
- the comment for the steel paxel says "Bronze" instead of "Steel" because of copypasta

netherores.zs
- is blank, should be removed

**Comment by BBoldt** [comment]
@Fuhrmaaj 

What do you mean by there being no formatting for the first 3?

dimstorage.zs is only there because atlauncher isn't wiping old script files on updates.

**Comment by Fuhrmaaj** [comment]
http://imgur.com/P623TSg

Hopefully you can see what's going on here, this is the server file for two different scripts. The Archimedes Ships scripts has no breaks for whatever reason, and the comments run into each other but somehow it still works. The Binnie's scripts are an example of what the formatting looks like when you put it in originally.

If your scripts look good then I'll try deleting them at the update and see if they get regenerated. I'll delete dimstorage.zs client-side, thanks.

**Comment by BBoldt** [comment]
Turns out Notepad++ saved them in unix format somehow...?

Anyways, I've fixed the issue.

Also, look at all this messy code I've cleaned up!
![](http://i.imgur.com/xFj0D63.png)

:stuck_out_tongue:

**Comment by BBoldt** [comment]
Oh, I did this I think.
