### ISSUE TITLE
Ender I/O Powered spawner

### ISSUE THREAD

**Issue by dylanpiera** [BBoldt/Unabridged#244]
I want to make a villager farm with ender i/o only villagers are on the blacklist for being spawned
when i empty the blacklist its still blacklisted in game

il show the config soon (can't atm)

Anyone know how to fix

**Comment by dylanpiera** [comment]
{

  "_comment": "New entities are added, one already in _Core will have their values replaced with those in this file",
  "costMultiplier": {
  },
  "_comment": "Adding a blackList section will complete replace the one in the core file"
  "blackList": [
  ]
}
}

**Comment by Fuhrmaaj** [comment]
It looks like you've got one brace too many. Other than that what you've written looks correct so it should work.

**Comment by dylanpiera** [comment]
Sorry but whice one is the brace??


also, my pc just died
so.. lets hope i can recover my world :(

**Comment by Fuhrmaaj** [comment]
These are braces {}
These are brackets []
These are parentheses ()

I see 2 left braces and 3 right braces. That sucks about your computer, let me know how it goes!

**Comment by BBoldt** [comment]
This is not an issue with the pack. I can't give support for every single personal change you want to make.
Same goes for crashes and issues caused by extra mods you have added to the pack, I simply don't have the time to support stuff like that.
