### ISSUE TITLE
Reliquary Ender Shot crashes server

### ISSUE THREAD

**Issue by Fuhrmaaj** [BBoldt/Unabridged#248]
I made the Hunter's Handgun from Reliquary, loaded up Ender Shot and crashed the server within a second or two of firing it. After the server restart, I tracked down the loot from the squid I killed then shot another squid and the server crashed again.

Crash Logs:
http://pastebin.com/nz7H8EDL

**Comment by BBoldt** [comment]
Hunter's Handgun disabled until it gets fixed.
