### ISSUE TITLE
Add stuff to Forestry configs

### ISSUE THREAD

**Issue by Fuhrmaaj** [BBoldt/Unabridged#250]
I'm just gonna leave this here because I keep meaning to do it but then forget about it when I stop playing.

Backpacks should be configured to be able to pick up items from other mobs (ore, mob drops, building blocks if I'm ambitious).

Mod flowers (BoP, PMP) can be added to the Apiculture config so that they breed around more flowers and they'll also create the flowers while running. A grievance I have with BoP is that not all of the resources are renewable, but we can at least make the flowers renewable with this config option.

**Comment by BBoldt** [comment]
Doesn't BoP generate flowers around hives already??

PMP has A FUCK TON of flowers. I considered adding aspects for them, but it would take me like a year.

**Comment by Fuhrmaaj** [comment]
Just one flower generates from my experience, in FTB:Unleashed there were about a dozen BoP flowers which would generate. Adding the flowers to the config is pretty easy, I just have to get around to doing it. I don't know how to add aspects to items, but it seems like it would be a pain.

**Comment by BBoldt** [comment]
Closing this
