### ISSUE TITLE
Turn of Galacticraft Space Race message

### ISSUE THREAD

**Issue by Fuhrmaaj** [BBoldt/Unabridged#261]
The message pops up after you die, and causes you to get killed again

**Comment by BBoldt** [comment]
if you can figure out how, you become winner

**Comment by BBoldt** [comment]
https://github.com/micdoodle8/Galacticraft/issues/1180

**Comment by BBoldt** [comment]
Because I can't fix this personally, I'm closing the issue.

They know about the problem.
