### ISSUE TITLE
Aether2's Cosmetic Ring recipe overrides AdvGen's Iron Frame

### ISSUE THREAD

**Issue by MechaJ** [BBoldt/Unabridged#272]
possible fix using minetweaker:
[
recipes.addShapeless(<advgenerators:IronFrame> * 2, [<aether:ironRing>]);
]

tested, and for some reason less than and greater than symbols are not appearing

**Comment by MechaJ** [comment]
Whoops, supposed to output two IronFrame instead of one

**Comment by BBoldt** [comment]
```
/* Advanced Generators
   Tweaks and Alterations */

// Iron Frame
recipes.remove(<advgenerators:IronFrame>);
recipes.addShaped(<advgenerators:IronFrame>, [[<ore:ingotIron>, null, <ore:ingotIron>], [null, null, null], [<ore:ingotIron>, null, <ore:ingotIron>]]);
```

my fix

**Comment by BBoldt** [comment]
also to put code on github you do this:

```
```
CODE
```
```
