### ISSUE TITLE
Client crash from NEI + AE2

### ISSUE THREAD

**Issue by Fuhrmaaj** [BBoldt/Unabridged#274]
When using NEI to put the ingredients for a recipe into the crafting table of the AE2 Crafting Terminal, the client crashes if any ingredient is missing. I got Mecha to test too and he crashed as well with a different recipe. This is when you shift-click on the question mark to place the ingredients. I've tested in a TiC Crafting Station and it didn't crash when I didn't have the ingredients.

**Comment by BBoldt** [comment]
Tried in the latest version, not happening for me. 

Try again after RC 4
