### ISSUE TITLE
[bug] quarry re-mines empty layers in Deep Dark

### ISSUE THREAD

**Issue by MechaJ** [BBoldt/Unabridged#279]
http://forum.feed-the-beast.com/threads/1-0-3-quarry-stops-mining-after-a-few-minutes.61072/

**Comment by MechaJ** [comment]
Pandolfo says he was able to get around this by moving quarry to lower level of Deep Dark, the quarry seems to not like the huge open space below

**Comment by BBoldt** [comment]
https://github.com/BuildCraft/BuildCraft/issues/2322

**Comment by BBoldt** [comment]
I don't know what to do about this.
