### ISSUE TITLE
[bug] forestry carpenter recipe for paper using wood pulp doesn't work

### ISSUE THREAD

**Issue by MechaJ** [BBoldt/Unabridged#284]
![2015-04-04_03 02 45](https://cloud.githubusercontent.com/assets/8594580/6991950/c4a3019a-da77-11e4-83f7-fc530966f67d.png)

also, none of the recipes that use wood pulp seem to be working in the carpenter

**Comment by BBoldt** [comment]
Even worse, NO recipes seem to be working in the carpenter.

**Comment by BBoldt** [comment]
http://jenkins.ic2.player.to/job/Forestry_Dev/515/changes

**Comment by BBoldt** [comment]
Fixed in RC4
