### ISSUE TITLE
[bug] mekanism universal cable energy consumption

### ISSUE THREAD

**Issue by MechaJ** [BBoldt/Unabridged#290]
mekanism universal cable constantly consumes energy if connected to a cryo-stablized redstone conduit

**Comment by BBoldt** [comment]
You're not really supposed to connect mekanism cables directly to other cables.

You should probably use a buffer.

Does this happen with all thermal dynamics flux ducts or just the cryo stabilized ones?

**Comment by BBoldt** [comment]
Closing this, it's a funky mod interaction that I can't do much about. 

Likely if I report this to mekanism or team cofh, they will just say "don't do that".

Feel free to report it to them if you want though, I would suggest reporting it to mekanism,
