### ISSUE TITLE
[?] Deaths in The End have unsafe inventories

### ISSUE THREAD

**Issue by MechaJ** [BBoldt/Unabridged#293]
Krumble died in the End, and I came upon items spilled on the ground, which is strange as Gravestones is supposed to prevent that, and Soulbound didn't trigger for the soulbound items either!

Today Krumble died in the End, and he says he got a message saying his void chest has new inventory.  could be a false detection of death that void chest would save items from.  Later I came by and found an Aether Coin on ledge, nothing else. Or maybe the void chest has to be put into world before they can hold inventory. Or maybe how inventory after death is handled is bugged and just not behaving in any predictable way in The End.

In any case, more investigation is required.

**Comment by Fuhrmaaj** [comment]
I figured out a fix. Stop dying in the End.
