### ISSUE TITLE
Rework heart canisters to give you absorption instead of the tcon heart system, as it is broken

### ISSUE THREAD

**Issue by BBoldt** [BBoldt/Unabridged#296]

**Comment by BBoldt** [comment]
Done.

@Fuhrmaaj you're going to need to forcibly remove heart canisters from anyone who may have them

**Comment by Fuhrmaaj** [comment]
uh, what happens if I don't?

**Comment by BBoldt** [comment]
well, a couple players on your server right now are completely invincible

the heart canister system glitched out and kept going up

I think mecha and shadow experienced this
