### ISSUE TITLE
Fix uranium god damnit

### ISSUE THREAD

**Issue by BBoldt** [BBoldt/Unabridged#299]
Also add a special recipe to turn uranium into yellorium.

**Comment by Fuhrmaaj** [comment]
What were you thinking for this? You could just use the config option to let Big Reactors use Uranium.

**Comment by BBoldt** [comment]
No.

Uranium isn't yellorium, but it's close. I'm going to add an alloy recipe, uranium + yellow dye = yellorium.

**Comment by BBoldt** [comment]
Fixed.
