### ISSUE TITLE
Most recent crash

### ISSUE THREAD

**Issue by BWhite1** [BBoldt/Unabridged#304]
Loaded into game fine, Joined multi-player before crashing after loading for about 2 minutes.

https://gist.github.com/BWhite1/2d65075bd191b7da0b17

**Comment by BBoldt** [comment]
ha looks like your warded blocks fucked up somehow

**Comment by BBoldt** [comment]
https://github.com/Azanor/thaumcraft/issues/1550

Issue is still open.

**Comment by BBoldt** [comment]
Azanor gives no fucks, therefore I have no choice but to not give any either and close the issue.

Sorry.
