### ISSUE TITLE
Archimedes Airship turned pink when parked a second time

### ISSUE THREAD

**Issue by MechaJ** [BBoldt/Unabridged#306]
![2015-04-22_02 00 09](https://cloud.githubusercontent.com/assets/8594580/7268867/53954498-e893-11e4-816b-8f7ced4ac65f.png)
 Looks way better, though

**Comment by BBoldt** [comment]
nothing I can do, enjoy your pink ship

**Comment by darkevilmac** [comment]
Pretty.
