### ISSUE TITLE
[anti-synergy] Can't mutate Wormwood due to crop auto-replant

### ISSUE THREAD

**Issue by MechaJ** [BBoldt/Unabridged#307]
Is it possible to turn off the crop auto-replant temporarily? Another possible workaround would be recipe that does durability damage to a Mutating Sprig, with four wispy cotton around a wheat/seed for a wormwood seed.

**Comment by BBoldt** [comment]
if it's causing trouble i'll just disable

**Comment by BBoldt** [comment]
fixed in next version
