### ISSUE TITLE
[bug] right clicking to place down a fuel drum results in no fuel drum

### ISSUE THREAD

**Issue by MechaJ** [BBoldt/Unabridged#313]
![2015-04-30_03 23 25](https://cloud.githubusercontent.com/assets/8594580/7409056/b1ef125c-eee8-11e4-810e-9c91d0eb5302.png)

here's a picture of a lack of fuel drum on my third test.  I maybe shouldn't have used full fuel drums for these tests.  Just to be clear, there is no drum at all after clicking

**Comment by BBoldt** [comment]
Can't reproduce, maybe it's a server issue?

Like, a server lag issue. idk
