### ISSUE TITLE
Issue "java.lang.IllegalStateException: Splash thread" on OS X

### ISSUE THREAD

**Issue by BBoldt** [BBoldt/Unabridged#326]
It seems the new forge loading GUI isn't working correctly on certain versions of OS X.

To fix this yourself, navigate to your config folder, and edit the file "splash.properties"

set ```enabled=true```

to ```enabled=false```

**Comment by Drullkus** [comment]
That tag x3

**Comment by BBoldt** [comment]
Related: https://github.com/MinecraftForge/FML/issues/644

Feel free to post the logs there if you follow their instructions. I can't get them myself as I am not experiencing the issue.

**Comment by BBoldt** [comment]
Going to disable the loading screen for now.
