### ISSUE TITLE
"BOP New Grass" crash

### ISSUE THREAD

**Issue by TCzelusniak** [BBoldt/Unabridged#328]
Third time I got this crash, did the whole, "Remove erroring entities" from the forge config to fix it once but it comes up in different areas than where I did the remove entities. Not really sure what the main cause is other than some grass block that I don't see. 

https://pastee.org/tm9b2

**Comment by BBoldt** [comment]
Found it: https://github.com/Glitchfiend/BiomesOPlenty/issues/442

Fortunately it was fixed about a week ago in BOP, I'll make sure to update to the fixed version during the next pack update.
