### ISSUE TITLE
Movement "stuck" when going from grass to dirt

### ISSUE THREAD

**Issue by Skar78** [BBoldt/Unabridged#331]
Hi,

I experienced now several times that during a running SP game suddenly the movement would be stuck when i cross from a dirt to a grass block. This typically occurs after some game time has passed, like after 30+ min of playing.

This is similar to being stuck on a wall/ceiling/door but once it occurs its reproducible and happens on the edge between a grass block and a dirt block. Very slowly (think quicksand) I can get get unstuck.

With reproducible I do not mean that I can force it to happen, but if it happens it will stick around and every time i cross a dirt/grass block border i get stuck and once i break free turn around and try it again it happens again. This will go on and happen than on ALL grass/dirt block borders, not just a speciifc one.

I know that this issue sounds like crap and probably all kinds of info are missing to help you to even check this. I am 5 days gone on a trip and once I back I will spend more time to track this down as its such a major annoyance.

("Default ressource pack" here.1.01a - I am not sure but i think I loaded F32 in between and removed it again, not sure. No mods added, no special config changes, no issue with other packs.)

**Comment by Skar78** [comment]
i have also a hard time to reproduce this -.-

**Comment by BBoldt** [comment]
It looks kinda like the blocks you just dug didn't actually disappear.

If this happens again, try reloading the world and see if there are blocks there.

**Comment by Skar78** [comment]
Over time I kind of felt that´you are right. some client side issue not really de-registering, or however to call it, the blocks.
It seemed to happen more often on SP. I changed by now to a server that i run on the same pc and never experienced this again.

**Comment by BBoldt** [comment]
Closing. If you obtain any more information about this, reopen it or make a new issue.
