### ISSUE TITLE
[crash] random CTD crashlog (java.util.ConcurrentModificationException)

### ISSUE THREAD

**Issue by MechaJ** [BBoldt/Unabridged#333]
http://pastebin.ca/3007609

teleported back to private base, insta-crash to desktop.  Just posting for your prying eyes.

**Comment by krumble1** [comment]
I just had this happen as well. http://pastebin.com/0vESSn3x

**Comment by BBoldt** [comment]
¯\(°_o)/¯

**Comment by Xaethon** [comment]
Common fastcraft crash, I think downgrading to fastcraft 1.19 fixes it.

**Comment by BBoldt** [comment]
Don't think this is happening anymore
