### ISSUE TITLE
[SUGGESTION] SYNGAS PRODUCER SHOULD ACCEPT CHARCOAL BLOCKS

### ISSUE THREAD

**Issue by krumble1** [BBoldt/Unabridged#338]
Syngas producer from Advanced Generators accepts (among other things) coal blocks, coal, charcoal, coal dust, and charcoal dust, but not charcoal blocks. Please add support for charcoal blocks from Mekanism (and maybe the ones from Garden Stuff), with the same carbon value as coal blocks.

Title credit goes to @TehNut

**Comment by TehNut** [comment]
WELL.

**Comment by MyDeloreanWontStart** [comment]
wtf

**Comment by TehNut** [comment]
ftw
