### ISSUE TITLE
Crafting compressed cobblestone is prevented by roadblocks

### ISSUE THREAD

**Issue by krumble1** [BBoldt/Unabridged#339]
When trying to craft compressed cobblestone from Extra Utilities I instead get the Roadblocks' version of the same name.

**Comment by SgtPunishment** [comment]
Sorry about that! I'll fix it A.S.A.P. for now I would suggest MineTweaker for a temp fix @BBoldt

**Comment by BBoldt** [comment]
no too late, you're fired @SgtPunishment

**Comment by SgtPunishment** [comment]
NNNNNNNNNUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU IMAFIXINGITNAOW!

**Comment by MyDeloreanWontStart** [comment]
ded
