### ISSUE TITLE
[missing conversion] darksteel needs conversion from liquid to ingot/block

### ISSUE THREAD

**Issue by MechaJ** [BBoldt/Unabridged#340]

**Comment by Drullkus** [comment]
Thermal Smeltery and ExtraTCon both add Dark Steel. This causes recipes to not show up in NEI. The recipes still work.

**Comment by BBoldt** [comment]
It actually does show in NEI, but only if you look at the recipe for the block or ingot.

It's definitely castable.

**Comment by BBoldt** [comment]
![](http://i.imgur.com/EEcrrIn.png)
