### ISSUE TITLE
Teleporting between two RFtools teleporters sometimes crashes client

### ISSUE THREAD

**Issue by jeviuss** [BBoldt/Unabridged#342]
I was teleporting from Mecha's base to my base and crashed upon arrival at my base. Has happened while traveling to Bboldt's and Cookies' on other occasions.

Pastebin of error:
http://pastebin.com/VFGfYXGz

**Comment by BBoldt** [comment]
https://github.com/BBoldt/Unabridged/issues/333

Related to ^
