### ISSUE TITLE
[config] Iguana's Tweaks disables smeltery obsidian creation

### ISSUE THREAD

**Issue by MechaJ** [BBoldt/Unabridged#343]
change "B:removeObsidianAlloy=true" to false in config/IguanaTinkerTweaks/main.cfg

**Comment by nin9abadga** [comment]
Do you know if anything else has changed in the config for Iguana Tweaks? I seem to have lost the xp gain for all my tools (as in they don't gain anymore) and my tools have "missing data" (specifically ardite pick and hammer). If i stick them back in the crafting window it resets the mining level to obsidian. Have i missed something? Is there an option somewhere i've missed?
