### ISSUE TITLE
oreberry dimlets exist

### ISSUE THREAD

**Issue by BBoldt** [BBoldt/Unabridged#345]
fix it

**Comment by timo103** [comment]
Because oreberrys are the most op thing.

**Comment by BBoldt** [comment]
they aren't even functional if you have them

**Comment by MyDeloreanWontStart** [comment]
oh rly. .. there's essence bushes from somewhere on ote that would disagree

**Comment by BBoldt** [comment]
essence bushes aren't oreberry bushes

**Comment by MyDeloreanWontStart** [comment]
huh til
