### ISSUE TITLE
Server Crash upon opening Flaxbeard Book

### ISSUE THREAD

**Issue by Xaethon** [BBoldt/Unabridged#347]
Esteemed Innovation causes a server crash when opened with shift right click. This is one of the books you get from the spawn bag.

https://panel.otegamers.com/public/log/154

Pretty sure it's been reported to the devs multiple times, ages ago and they still haven't fixed it.

**Comment by BBoldt** [comment]
Their issue seems to be fixed, and your log is empty.
https://github.com/Esteemed-Innovation/Flaxbeards-Steam-Power/issues/168

**Comment by BBoldt** [comment]
Closing. If you can provide a log proving this still happens, reopen the issue.
