### ISSUE TITLE
[bug?] Exchanging endermen head types also produces skeleton heads

### ISSUE THREAD

**Issue by krumble1** [BBoldt/Unabridged#353]
When using the AE system's crafting interface to exchange the enderman head from Iguana Tinker Tweaks into EnderIO's version, shift-clicking stacks at a time gives the player not only the expected EnderIO heads, but also a similar amount of vanilla skeleton skulls.

**Comment by BBoldt** [comment]
o.O

**Comment by BBoldt** [comment]
Can't really fix this.
