### ISSUE TITLE
[bug] natual mob caps in dimensions seems to not work in RFTools dimension

### ISSUE THREAD

**Issue by MechaJ** [BBoldt/Unabridged#354]
just cofh killalled the 3 basic mob types, due to a RFTool dimension that was being pumped out killing the server.  90 zombies, 18 skeles, 908 creepers.  Mob caps don't seem to be working, as a dark cave becomes a mob rave very quickly.  This kills the server eventually.
![2015-06-05_02 55 07](https://cloud.githubusercontent.com/assets/8594580/8001841/577c4764-0b2f-11e5-9783-9bf4d58b5a96.png)
the above is xray vision due to 1 FPS into a sphere on bottom of the ocean, the flaming skeletons from SpecialMobs, I do think

and I just noticed the lower left of the image, hahaha.  Now the creeper count makes more sense.

**Comment by BBoldt** [comment]
This still an issue?

**Comment by BBoldt** [comment]
Closing until it happens again (if it's still an issue).
