### ISSUE TITLE
Could you add some custom alloys? 

### ISSUE THREAD

**Issue by BBoldt** [BBoldt/Unabridged#356]
Extra TIC+metallurgy has these by default, for some reason its not oredict compatible. Should be easy enough to asds.
Brass Smeltery Recipe: fuck the crucible, earlygame grind, hard to automate without dropped items and shit everywhere. 2 zince and 1 copper alloy to cast flaxbeard brass. Maybe also add it to induction smelter and alloy furnace.

-- MyDeloreanWontStart

**Comment by MyDeloreanWontStart** [comment]
*raises hand*


do this

**Comment by MyDeloreanWontStart** [comment]
yaaay

**Comment by BBoldt** [comment]
I just added it to tcon as an alloy. Also made sure to add all relevant casting recipes and such.

Bluepower adds a way to get it too.

**Comment by MyDeloreanWontStart** [comment]
Aha cool. Thanks bro :)
