### ISSUE TITLE
Get rid of some thaumonomicon tabs??

### ISSUE THREAD

**Issue by MyDeloreanWontStart** [BBoldt/Unabridged#357]
like AOBD and RC, that add like 2 items per tab, and move them to other tabs

**Comment by BBoldt** [comment]
I might be able to do that. Not sure how powerful modtweaker is in that regard.

**Comment by MyDeloreanWontStart** [comment]
Oh it can do it. I saw a post on /r/feedthebeast about it a while ago but I can't seem to find it.

**Comment by BBoldt** [comment]
I'll figure it out then. I agree it should be tidied up a bit. Wish I could do the same for the creative tabs.

**Comment by MyDeloreanWontStart** [comment]
I think theres a coremod somewhere that can....

**Comment by BBoldt** [comment]
Seems like a pain in the ass, I can't just move researches, I would have to remove and recreate them in another tab.

http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Thaumcraft_4_Support:Research

**Comment by Yulife** [comment]
Here you go BBoldt ;)

http://forum.feed-the-beast.com/threads/1-7-10-thaumcraft-addon-witching-gadgets.68492/page-3#post-997867

**Comment by MyDeloreanWontStart** [comment]
AHA THATS WHERE I SAW IT THANKS
