### ISSUE TITLE
Constantly getting timed out

### ISSUE THREAD

**Issue by raxixor** [BBoldt/Unabridged#358]
I installed the pack two days ago, and it ran fine the first time I launched it, but then something happened with the minecraft servers, and it stopped working. Every time anyone tried to join it disconnects them with "Timed out". I created a new world and it still happens. I can post my logs to pastebin.

I also removed Thermal Recycling, because it was having problems.

**Comment by BBoldt** [comment]
Do you have any problems running other packs or vanilla MC after that "issue with the minecraft servers" occurred?

Also, I definitely can't do anything without logs. Nobody else has reported this issue.

**Comment by raxixor** [comment]
Other packs or vanilla worked just fine.
The issue was auth servers being down for a sec, and the console showing an error connecting with minecraft servers.

Logs:
latest.log http://pastebin.com/wZB6ubPx
fml-server-latest.log was too long, so I put it elsewhere:
https://drive.google.com/file/d/0B4bZ3nfvmRqIUngxcWFCemJsT2s/view?usp=sharing

**Comment by BBoldt** [comment]
There isn't much I can do about this. 

Just make sure you and your server are both running java 8.
