### ISSUE TITLE
Botania's Sojourner's Sash

### ISSUE THREAD

**Issue by kkitsune** [BBoldt/Unabridged#359]
The sash does not add step-assist! This was a know bug on Botania's side that has been fixed, so can it be possible to update it a bit?

**Comment by BBoldt** [comment]
Wrong. It's a bug on the Aether's side. Aether team has refused to fix it and have abandoned Aether 1.7.10 for an Aether rewrite for 1.8.

Therefore I'm going to be removing the Aether, to fix this step assist issue and to fix several other issues. Either wait until next update or remove aether, aether aspects, and gilded games util yourself.

**Comment by MyDeloreanWontStart** [comment]
Whoa, removing aether? Cool, I didnt like that in the pack. Too much unneccessary bloat.
