### ISSUE TITLE
[server crash] Twilight Forest biome/mob weirdness

### ISSUE THREAD

**Issue by MechaJ** [BBoldt/Unabridged#361]
http://pastebin.ca/3023335
plus
"STDOUT/]: [twilightforest.entity.ai.EntityAITFThrowRider:func_75249_e:68]: throw!" was the last line before the crash in the server log

**Comment by BBoldt** [comment]
Looks like RF Tools fucked up trying to use a twilight forest biome in a custom dimension.

**Comment by BBoldt** [comment]
this was probably a one off thing, if it happens again, let me know
