### ISSUE TITLE
Placed down a slime block, got dismembered somehow, world melted

### ISSUE THREAD

**Issue by MyDeloreanWontStart** [BBoldt/Unabridged#362]
what the fuck

![](http://i.imgur.com/we08vKx.png)
also couldnt move other than flying up and down
![](http://i.imgur.com/iPRqWzs.png)

![](http://i.imgur.com/UEK8aQc.png)

![](http://i.imgur.com/UBaNFWd.png)

![](http://i.imgur.com/RqjqE6P.png)

![](http://i.imgur.com/TXfLJzx.png)
Every time i place an et futurum slime block this happens

**Comment by MyDeloreanWontStart** [comment]
Thank you for the esteemed status of "what the fuck". Exactly my reaction

**Comment by ganymedes01** [comment]
- Do you have to touch the slime block in order for this to happen or is just placing enough?
- If you break it does the world go back to normal?
- Which black magic cult do you take part in?

**Comment by MyDeloreanWontStart** [comment]
Placing is enough.

Sometimes if I go to main menu and rejoin, it's fine, other times the world is unplayable.

Time police

**Comment by ganymedes01** [comment]
Do you use optifine or similar?

**Comment by MyDeloreanWontStart** [comment]
Nope. It happened first with some custom mods, but is reproducible in normal unabridged. Not sure of other modpacks tho

**Comment by ganymedes01** [comment]
- Does it happen 100% of the time? (sorry about the amount of questions, I can't reproduce it so I need as much information as I can get)
- Can you check if anything weird gets printed in the logs?

**Comment by MyDeloreanWontStart** [comment]
You should probably ask @BBoldt all these, Im retarded. I'll try though.

Sometimes it doesn't, like right now... haven't changed anything though.

Idk ill check logs if i find the glitch.

**Comment by BBoldt** [comment]
Sorry, I don't have the time to test this really. 
I'm just going to disable the slime block for now in my pack.
