### ISSUE TITLE
DISABLE ZTONES TOOLS

### ISSUE THREAD

**Issue by MyDeloreanWontStart** [BBoldt/Unabridged#365]
http://imgur.com/a/l7zP0

9 times ore duplication. With a single item. Found as dungeon loot. My balance gland just burst.

**Comment by BBoldt** [comment]
yep I saw you posting about that on reddit, way ahead of you

**Comment by BBoldt** [comment]
Didn't know that one existed.

**Comment by MyDeloreanWontStart** [comment]
Yeah, its op as fuck. Kill it.

**Comment by Yulife** [comment]
Why is that even in a decoration mod

**Comment by MyDeloreanWontStart** [comment]
Ikr....

**Comment by BBoldt** [comment]
![](http://i.imgur.com/lzy6ZYk.png)

Gone completely :D

**Comment by BBoldt** [comment]
Leaving in the ofanix, while it can be used for kinda cheap cobblegen, it is also used for a lot of crafting stuff.

**Comment by MyDeloreanWontStart** [comment]
Coool.
