### ISSUE TITLE
[client crash] thermal expansion machine / enderio conduit

### ISSUE THREAD

**Issue by MechaJ** [BBoldt/Unabridged#373]
I put item conduit behind machine, went into phytogenetic thermal expansion machine thing's gui, right clicked to change backside of machine to output, and client crashes upon loading the area a few times.  Reloading server deleted the conduit, which stopped client crashing.  I then picked up machine, proceded to set up conduits and all without problem on second go of it.

http://pastebin.ca/3033869

**Comment by BBoldt** [comment]
Tried to do what you said, could not reproduce

I think it got fixed when I updated eio last update
