### ISSUE TITLE
Problems Connecting to Unabridged Server v3 over the internet

### ISSUE THREAD

**Issue by saitozero** [BBoldt/Unabridged#374]
I have been running a server on a secondary PC in my home for the last few weeks. My buddy and I have been playing on it and having few issues. However, last night I updated to v3 and major problems started.
I had no issue connecting to the server locally over my intranet or by connecting through my external IP address. However, when my buddy tried to log on today he always had either time outs or has a "fatal error." We have tried everything to try and isolate the problem. The server, host machine and routers have been reset by both of us. I sent him a copy of my instance and server, and he can run the server and connect on his intranet just fine, with either instance. If I try to connect to his machine I also get fatal errors. Server and instance files have been re-downloaded by both of us. I tried starting a fresh world and we have the same issue. I tried creating a vanilla server and it was flawless. The only thing we saw in the log was a mod mis-match on Morpheus and Tails. We tried adding Morpheus to the clients and taking Tails off the server and clients and it didn't work. We tried disabling Aromabackup and that didn't work. We don't know what else to try. Here are all the log files generated from the last server I installed, we both tried to log onto it, I am saitozero and he is Hadurac. Hadurac is the one who cannot log on.  I am hosting the server on a Windows 7 machines and playing from a Windows 8.1 machine.  Hadurac is playing and hosting from a Windows 7 machine.

[2015-06-21-1.log.gz](https://drive.google.com/file/d/0Bz_xMmtfX2lbOXhWUDJCUnA1OXc/view?usp=sharing)
[fml-junk-earlystartup.log](https://drive.google.com/open?id=0Bz_xMmtfX2lbOXhWUDJCUnA1OXc&authuser=0)
[fml-server-1.log](https://drive.google.com/open?id=0Bz_xMmtfX2lbanI4RzdSNWhYUGs&authuser=0)
[fml-server-latest.log](https://drive.google.com/open?id=0Bz_xMmtfX2lbZzVkYjJtd0xGR0k&authuser=0)
[latest.log](https://drive.google.com/open?id=0Bz_xMmtfX2lbN1lnQWRrUDNMRWc&authuser=0)

Thank you.

**Comment by BBoldt** [comment]
I think it may be an issue with aroma backup and aroma1997core.

If you have those 2 mods on the server, you need them on the client or it wont work.

**Comment by saitozero** [comment]
When I first updated to the v3 server I installed aromabackup on the server and not on my client and you are right, it will not let you on.  However, the log will tell you that aromabackup is required so I added it to my client and then I was able to log on over my intranet.  I told me buddy this from the start when he updated so I know he had it installed as well.  I do not think this is the problem.

**Comment by Githubaccountlol** [comment]
Impossible to tell if you are having the same issue, but the solution for the connection issues I and many others had (failing to finish connecting & getting dropped by a 20-second timeout, or simply not progressing to 'downloading terrain' at all) was to change from java 7 to 8.

**Comment by saitozero** [comment]
Alright, after purging java 7 and installing java 8 64 bit on all PC's this has solved my issue.  Thank you very much Githubaccountlol, all the internet points to you.

**Comment by BBoldt** [comment]
I guess Java 8 is required for some mods now. Interesting.

Might want to do a little PSA about that on the subreddit.
