### ISSUE TITLE
[error from logs] chickenbones vs anything else that saves chunks, in this case aromabackups

### ISSUE THREAD

**Issue by MechaJ** [BBoldt/Unabridged#375]
http://pastebin.ca/3037051

this been appearing every once in a while, but without mobius wasn't getting enough info.  Now, here it is.

**Comment by BBoldt** [comment]
ლ(ಠ_ಠლ)

Why chickenbones

whyyyyyy

**Comment by BBoldt** [comment]
we don't have aromabackups anymore

and chickenbones is gonna chickenbone
