### ISSUE TITLE
Crash caused by crafting a golemancer's bell in an arcane worktable.

### ISSUE THREAD

**Issue by AuricPolaris** [BBoldt/Unabridged#376]
Title says it all. 

This is on a local basic forge server: http://pastebin.com/h8HeaS99

This is on a kcauldron server: http://pastebin.com/5FFyMPMA

It works in single player though!

Let me know if you need anything else BBoldt. :)

**Comment by BBoldt** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2361575-thaumic-horizons-v1-1-6-thaumcraft-4-addon?comment=1785

**Comment by BBoldt** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2361575-thaumic-horizons-v1-1-9-thaumcraft-4-addon?comment=1841

**Comment by BBoldt** [comment]
This randomly fixed itself apparently
