### ISSUE TITLE
Crash from Logistics Pipes / Forestry

### ISSUE THREAD

**Issue by billm** [BBoldt/Unabridged#377]
Best guess without looking too deep is that there was a forestry update in release 3 that contained an API change and logistics pipes wasn't updated to match.  This crash happened three times, once after a pipe was reconnected (don't have exact setup), once after server load and chunk load, and again after we restored and reconnected pipe.

Crash log: http://pastebin.com/ih11aKaz

**Comment by BBoldt** [comment]
I've updated logistics pipes to the very latest version twice since this issue was made. 

If this happens again after Release 5, reopen the issue.

**Comment by billm** [comment]
Looks like the issue was fixed in http://ci.thezorro266.com/view/Logistics%20Pipes/job/LogisticsPipes-0.9-mc17-bc7/16/changes - a shame that update didn't make it into release 4 (still showing 0.9.1.15), but I agree, this should be fixed for release 5 as long as you are pulling in at least 0.9.1.16.

**Comment by BBoldt** [comment]
Release 5 is coming very soon
