### ISSUE TITLE
Thaumic Horizon and Biomes O Plenty ID conflict

### ISSUE THREAD

**Issue by AuricPolaris** [BBoldt/Unabridged#378]
Both the Biomes O Plenty Bamboo Forest Biome and the Thaumic Horizon's Pocket Plane Biome have the Biome ID of 69. Causes some bizzare and possibly laggy biome generation. (If there is a duplicate ticket of this, I couldn't find it BBoldt person of modpacks!)

**Comment by BBoldt** [comment]
nope that's a new one

I'll get it fixed by next update

**Comment by BBoldt** [comment]
Going to have to change the id of bamboo forest. >.>

**Comment by AuricPolaris** [comment]
Had to do that here as well, we utilized 135 as the new biome ID for bamboo forest and this resolved the issue for now. Hopefully the mod author will put in a config for this in the future.

**Comment by BBoldt** [comment]
I picked 169, but I'll change it to 135 so it doesn't cause any changes for your server
