### ISSUE TITLE
Wildcards not supported in Mekanism Cardboard Box blacklist

### ISSUE THREAD

**Issue by Githubaccountlol** [BBoldt/Unabridged#380]
Half the entries in the blacklist are currently broken.

Currently the cardboard box blacklist file looks similar to this

```
# Thaumcraft
Thaumcraft:blockWarded:0
Thaumcraft:blockCosmeticOpaque:2
Thaumcraft:blockArcaneDoor:*
Thaumcraft:blockStoneDevice:*
Thaumcraft:blockAiry:0

# Carpenter's Blocks
CarpentersBlocks:blockCarpentersSafe:*

# IC2
IC2:blockPersonal:*

# Twilight Forest
TwilightForest:tile.TFBossSpawner:*
TwilightForest:tile.TFTowerDevice:*
TwilightForest:tile.TFTowerTranslucent:*
```

Because the mek parser for this file looks for an integer in the last split section, asterisks don't work.

Hopefully this link is appropriate, I don't know what I'm doing on github.
https://github.com/aidancbrady/Mekanism/blob/6b765d27e73c30f78e2402b5bbab07d6c8647e33/src/main/java/mekanism/common/BoxBlacklistParser.java

As far as I can tell, there is no support currently for matching all meta values, so your options are:

Define each block & meta pair individually, and thus require maintenance when/if things change

or

Be a bit hacky and use the literal value of short.MAX_VALUE: 32767
I have tested this and it **does work** (my test block was one of the TF boss spawners that don't currently spawn anything and thus stay in the world long enough to click on), both parsing and actually working on the box.
Because the parser only handles integers but the blacklist API supports oreDictionary.WILDCARD_VALUE, this works.

Not my style, but !blame Brady.

IC2 doesn't exist, so that entry can be removed.

New list looks like this (disclaimer: I only modified the list that existed, I don't know what you're going for and what should/shouldn't be on it, my intention is to fix the fact that it doesn't work. For example, I don't know if the things you attempted to wildcard actually need wildcarding or not):

```
# Use this file to tell Mekanism which blocks should not be picked up by a cardboard box.
# Proper syntax is "ID:META". Example (for stone):
# 1:0

# Thaumcraft
Thaumcraft:blockWarded:0
Thaumcraft:blockCosmeticOpaque:2
Thaumcraft:blockArcaneDoor:32767
Thaumcraft:blockStoneDevice:32767
Thaumcraft:blockAiry:0

# Carpenter's Blocks
CarpentersBlocks:blockCarpentersSafe:32767

# Twilight Forest
TwilightForest:tile.TFBossSpawner:32767
TwilightForest:tile.TFTowerDevice:32767
TwilightForest:tile.TFTowerTranslucent:32767
```

For reference, the errors thrown to the log look like this:

```
[15:15:37] [Client thread/ERROR] [Mekanism/Mekanism]: BoxBlacklist.txt: Couldn't parse blacklist data on line 8
[15:15:37] [Client thread/ERROR] [Mekanism/Mekanism]: BoxBlacklist.txt: Couldn't parse blacklist data on line 9
[15:15:37] [Client thread/ERROR] [Mekanism/Mekanism]: BoxBlacklist.txt: Couldn't parse blacklist data on line 13
[15:15:37] [Client thread/ERROR] [Mekanism/Mekanism]: BoxBlacklist.txt: Couldn't parse blacklist data on line 16
[15:15:37] [Client thread/ERROR] [Mekanism/Mekanism]: BoxBlacklist.txt: Couldn't parse blacklist data on line 19
[15:15:37] [Client thread/ERROR] [Mekanism/Mekanism]: BoxBlacklist.txt: Couldn't parse blacklist data on line 20
[15:15:37] [Client thread/ERROR] [Mekanism/Mekanism]: BoxBlacklist.txt: Couldn't parse blacklist data on line 21'
```

**Comment by BBoldt** [comment]
Thanks for the help on this!
