### ISSUE TITLE
Cannot customize superflat worlds.

### ISSUE THREAD

**Issue by timo103** [BBoldt/Unabridged#382]
When I try to customize a superflat world or use a preset it changes to a biomes o plenty world when i hit done in the customization menu.

It spawns a biomes o plenty world, its not just in name.

I just want a desert superflat world so i dont have to clear a ton of grass.

**Comment by BBoldt** [comment]
https://github.com/FireBall1725/DefaultWorldGenerator/issues/2

**Comment by BBoldt** [comment]
mod removed
