### ISSUE TITLE
Flowing water client freeze with no crash report.

### ISSUE THREAD

**Issue by DeGariless** [BBoldt/Unabridged#390]
I was playing on [a server](https://www.reddit.com/r/MinecraftUnabridged/comments/3eqsus/the_moreorless_official_unabridged_server). I placed down water. It flowed out by I think 2 blocks and then the client became unresponsive. It seems as if the client is still communicating with the server even though the client is unresponsive. I am not able to log back into the server without another immediate client freeze. I tried re-installing the pack and removing fastcraft. Not sure what log you want but here is [fml-client-latest.log](https://www.dropbox.com/s/xa4vq4u7he8wc17/fml-client-latest.log?dl=1). If there is any more information I can give you, please let me know.

Windows 8.1 64-bit
Unabridged release 4

**Comment by MechaJ** [comment]
post logs plz

**Comment by DeGariless** [comment]
I posted a log already. Do you want a different log?

**Comment by MechaJ** [comment]
whoops, haha, you did post the log.  There doesn't seem to be a problem in the log, unless you changed out voxelmap or added another liteloader clientside mod.  Best I can guess is that you should delete the instance, install a fresh one.

**Comment by DeGariless** [comment]
That was the first thing I tried. I did not add any of my own mods to the
pack. Will try removing more client side mods and report back.

**Comment by BBoldt** [comment]
@DeGariless, @MechaJ is the one hosting the server you're trying to connect to, so i'm going to let him handle this one for now. If you guys discover a bug in the modpack let me know.

**Comment by DeGariless** [comment]
I have concluded that my computer does not like Aqua tweaks. I have no further information.
