### ISSUE TITLE
Compact machine interior not chunk loading

### ISSUE THREAD

**Issue by DeGariless** [BBoldt/Unabridged#398]
I made a compact machine with basic ore processing inside. I exited the compact machine and could not get it to process my ores. Upon further investigation,  I have found that the compact machine did not chunk load it's interior. This is technically not a bug because it is sat this way as a config option, but I don't see how compact machines will be useful without loading their interior. Was this intended?

**Comment by BBoldt** [comment]
Set like this intentionally, if you want it to chunkload you need to use a chunkloader. A while ago I had a lot of crashing issues with the chunkloading implemented in the mod.
