### ISSUE TITLE
Crash with BOP bucket of blood

### ISSUE THREAD

**Issue by BBoldt** [BBoldt/Unabridged#401]
https://gist.github.com/d6131ad86aaed330b0f9

**Comment by krumble1** [comment]
I was on fire from a trio of blazes, and placing/removing the blood to put out the fire on myself. Standing on nether brick, if that makes a difference. I'll see if I can do it again and record myself.

**Comment by BBoldt** [comment]
https://github.com/Glitchfiend/BiomesOPlenty/issues/541#issuecomment-141349547

**Comment by BBoldt** [comment]
need to make sure and update BOP in the next version of unabridged
