### ISSUE TITLE
Mekanism electrolytic separator ignores energy upgrades.

### ISSUE THREAD

**Issue by ArkeousAero** [BBoldt/Unabridged#404]
Placing energy upgrades in a mekanism electrolytic separator does not decrease energy usage. Instead the energy 'needed' tooltip increases.

**Comment by BBoldt** [comment]
https://github.com/aidancbrady/Mekanism/issues/2868
This looks like what you're talking about, and the dev says they have a reason for it.

Nothing I can do, if you want to discuss it, do it on that mek issue I linked.
