### ISSUE TITLE
Why can't I make paper tools?

### ISSUE THREAD

**Issue by timo103** [BBoldt/Unabridged#408]
You cant make paper tools at all.

**Comment by BBoldt** [comment]
go

**Comment by timo103** [comment]
bold i need paper tools

**Comment by timo103** [comment]
༼ つ ◕_◕ ༽つ Gib tools ༼ つ ◕_◕ ༽つ

**Comment by BBoldt** [comment]
¯\_(ツ)_/¯

**Comment by timo103** [comment]
gib tools

**Comment by BBoldt** [comment]
I got your tools right here

( ͡° ͜ʖ ͡°)

**Comment by timo103** [comment]
༼ つ ◕_◕ ༽つ Gib tools

**Comment by timo103** [comment]
I still cannot make paper tools

**Comment by timo103** [comment]
literally paper hitler

**Comment by timo103** [comment]
this is you

http://img02.deviantart.net/7407/i/2009/054/b/1/heil_hitler_by_orangedoom.jpg

**Comment by timo103** [comment]
this is you
![heil_hitler_by_orangedoom](https://cloud.githubusercontent.com/assets/7980635/9427016/b92dacc8-4932-11e5-8780-57b3230dd49c.jpg)

**Comment by TehNut** [comment]
@BBoldt I believe this is a clear sign that it's about time you finally added [this](http://minecraft.curseforge.com/mc-mods/228596-gib-_). It should only contain one entry: "minecraft:wooden_hoe" and give it at a fairly regular interval. Just for you, I'll make a new build that lets you specify players items are given to. I request this one only include Timo's name.

**Comment by timo103** [comment]
Oh, paper Goebbels shows his face.

**Comment by timo103** [comment]
but srs i need paper tools yo.

**Comment by BBoldt** [comment]
Iguana Tweaks - "Slime, Blue Slime, Paper, Cactus, and Obsidian can only be used for Tool Rods and Tool Bindings"

https://gist.github.com/0c25730c506778142c94
