### ISSUE TITLE
Tier 3 Galacticraft Rocket unfuelable

### ISSUE THREAD

**Issue by Platinumknyght** [BBoldt/Unabridged#417]
GalacticraftCore-1.7-3.0.12.350
Galacticraft-Planets-1.7-3.0.12.350
MicdoodleCore-1.7-3.0.12.350

So, fueling Tier 1 and Tier 2 rocket (placed on the same pad/ system of fueling) -> Everything was fine. Fueling doesn't engage on Tier 3 rocket. Found this:
    https://github.com/micdoodle8/Galacticraft/issues/1771
with the following fix:
    https://github.com/micdoodle8/Galacticraft/commit/2675afc95dcc02847f87d968c97bec29c46fca26

**Comment by BBoldt** [comment]
I'll make sure to update to the latest version in Unabridged Release 6, coming tomorrow.

If that doesn't fix it, we will have to reopen the gc issue.

**Comment by AuricPolaris** [comment]
Thank you BBoldt!

**Comment by BBoldt** [comment]
definitely fixed in release 6
![](http://i.imgur.com/OtrkDKt.jpg)

**Comment by BBoldt** [comment]
weeee
![](http://i.imgur.com/u50ZAwc.png)
