### ISSUE TITLE
90 second hang at start of both client and server launch

### ISSUE THREAD

**Issue by wugmump** [BBoldt/Unabridged#437]
"Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper" is the last log line. Doesn't happen if there's no connected network device, so it seems like it's a missing server of some kind.

**Comment by BBoldt** [comment]
hmm, i've been wondering about that

**Comment by BBoldt** [comment]
maybe it's some old update checker from a mod trying and failing to connect to a server

**Comment by BBoldt** [comment]
I don't know, sorry.
