### ISSUE TITLE
Add recipes/methods to aquire Knowledge Framgents

### ISSUE THREAD

**Issue by Nonsanity** [BBoldt/Unabridged#440]
As the Research Table game has gotten old and annoying for so many players, the alternate mode in Thaumcraft of buying research with primal aspect research points is the next best choice. However this requires far more primal aspect RPs than when using the game (where combo aspects can be used) and so is just as grindy as the game, in terms of time spent.

Knowledge Fragments are a source of RPs (they give one of each base aspect). Using these would reduce the time and gindiness to a tolerable level. Right now they can only be found, but they could be made renewable. Some options:

* Craft one of each aspect crystal and a book. (mining)
* Toss a book into a mana pool. (Botania)
* Add an AgriCraft crop which produces fragments. (AgriCraft)
* Add an Arcane Worktable recipe that uses stored aspects. (Thaumcraft)

More than one of these options could be added, if the quantities each outputs can be properly balanced so that no one option is more effective than any of the others.

**Comment by BBoldt** [comment]
All of these are feasible things I can do

**Comment by Nonsanity** [comment]
mods.botania.ManaInfusion.addInfusion(<Thaumcraft:ItemResource:9>, <minecraft:book>, 5000);

**Comment by BBoldt** [comment]
just did botania and the crafting recipe
