### ISSUE TITLE
Manasteel Mining Level weirdness

### ISSUE THREAD

**Issue by Skar78** [BBoldt/Unabridged#441]
Not sure if an issue, but I thought I better report it:

Added a manasteel pickaxe head to a bronze TiC pickaxe (head/handle were bronze, obsidian binding).
The tool was already master level and the result was only redstone mining level (?).

This already surprised me as the guide mentioned manasteel/thaumium and steel would be obsidian level. That is however only a part why i report this.

As I was rather desperate to get mining level obsidian (new world yay) I just checked the tooltips for adding a diamond - well I expected this should not work as i remember that the diamond should only give +500 dur but NOT the mining level.

However the result you see here: 
https://www.dropbox.com/s/363wl98fbc6m7dk/2015-10-08_162630.png?dl=0

I added another modifier (luck) after this, and it remained on this mining level.

If i put it in crafting the result is supposed to be:

https://www.dropbox.com/s/5poyoutuwpl42b1/2015-10-08_162710.png?dl=0 

I dont know why I would want to downgrade it. Not sure if a repair will screw it up or what happened here but it does not look like this is what was intended.

**Comment by BBoldt** [comment]
well, the mining level should be fixed in the next version hopefully

**Comment by BBoldt** [comment]
not sure what effect this will have on your tool, hopefully it fixes it
