### ISSUE TITLE
TiC Tools stop getting XP

### ISSUE THREAD

**Issue by Skar78** [BBoldt/Unabridged#443]
Hi,

My Lumber axe decided on skill level expert with 247 of 280 XP to stop getting XP from felling trees.

Disturbed by this I tested my Escavator - also stopped getting XP from Adept 17 of 1093.

I restarted the server. Issue remains. 

However my rapier still collects xp.

I have no clue what wrong - panicking - check logs nothing.
Ponder over a moment of frustration.

Decided to just keep felling some trees. Like 5 trees later suddenly it gets XP again. I check Excasvator also works again - wtf. 

Yes I know what tags this issue will get - but something is weird with 6b.

**Comment by BBoldt** [comment]
I doubt it's specifically version 6b of Unabridged that does this. It's most likely iguana tweaks' fault. Really have no idea though, I'm guessing maybe there is some server/client desync issue going on there? 

Nothing really I can do about it.

**Comment by BBoldt** [comment]
yep, nothing I can do
