### ISSUE TITLE
Vanilla recipe for gray dye doesn't exist on the client side.

### ISSUE THREAD

**Issue by DeGariless** [BBoldt/Unabridged#446]
To replicate issue the issue, place 1 bonemeal and 1 ink sack in crafting grid. notice that there is no result shown from the recipe. Click in the result space anyway to craft your gray dye.

**Comment by okyriosy** [comment]
I can't reproduce it.

**Comment by DeGariless** [comment]
Must be something on my end then. I will report back only if I have relevant information for you.

**Comment by BBoldt** [comment]
Also can't reproduce:

https://dl.dropboxusercontent.com/u/134976541/ShareX/2015-10/2015-10-24_11-45-26.mp4
