### ISSUE TITLE
NEI lies about chiseling ztones blocks

### ISSUE THREAD

**Issue by DeGariless** [BBoldt/Unabridged#447]
Some NEI recipes show 2 pages worth of chisel possibilities when only 1 page is actually accessable.

To replicate issue the issue, look up the zyth block in NEI. Right click on it in NEI to see the uses for the block. Scroll to the chisel tab and observe that that there are 2 pages of recipes for chisel. Now get out your chisel and try to access all of those recipes by putting a zyth block in the chisel. only 1 of the pages shows up.

**Comment by BBoldt** [comment]
That's because it's a one way recipe.

I need to add a way to get back to the base set of blocks,

You can chisel from base to zyth to zyth variants, but can't go back the other way.

**Comment by BBoldt** [comment]
fixed in release 8
