### ISSUE TITLE
Block ID corruptions?

### ISSUE THREAD

**Issue by AuricPolaris** [BBoldt/Unabridged#458]
Hi there BBoldt,

When I update from 0.7a to 0.8a, (even if I do it right :P) then we seem to get block ID corruptions. pastebins of what happens are below:

http://pastebin.com/BYSbk3cb
http://pastebin.com/ERQe5Vhj

Even with a backup, the server block IDs get corrupted. I removed thaumic energistics, and then another mod started doing it. Please advise!

Thank you and Regards,
Auric

**Comment by BBoldt** [comment]
You reverted to the backup before trying to update for the second time?

**Comment by BBoldt** [comment]
Did the server prompt you to do /fml confirm and did that run correctly?

**Comment by AuricPolaris** [comment]
I reverted the back up and the update. Server was fine. I then updated again and the Block ID corruption occurred. Server did not prompt me with /fml confirm.

**Comment by BBoldt** [comment]
When you get the chance, tell me if release 9 fixes this issue.
