### ISSUE TITLE
No longer getting string from Blue Power flax seed plants

### ISSUE THREAD

**Issue by hvdklauw** [BBoldt/Unabridged#459]
worked in the 0.7a release, no longer in the 0.8a release.

Not sure if the normal plants work, but the ones on agricraft sticks don't.

**Comment by meradudd** [comment]
Just tested and the BP flax seed plants harvest string just fine.  Flax seeds grown via Agricraft do not produce string either by harvesting (right-click) or pulling them up (left-click/rake).
