### ISSUE TITLE
Agricraft Lapis seeds not working in v8.a

### ISSUE THREAD

**Issue by meradudd** [BBoldt/Unabridged#460]
After the update, the lapis seeds state 'cannot grow here' despite having lapis ore underneath.  Replanting and/or relocating does not fix the situation.

**Comment by zeeZ** [comment]
It requires Nether Lapis Ore for some reason.

**Comment by meradudd** [comment]
Hrm....that's most odd.  this changed when we updated to v8.  Setting mis-aligned or something, I guess.  one quick trip into the Nether later.....yah, with Nether Lapis Ore it works just fine.
