### ISSUE TITLE
EnderIO fuels not working in Pneumaticraft

### ISSUE THREAD

**Issue by meradudd** [BBoldt/Unabridged#463]
Seems when we upgraded to release 9, something shifted.  My advanced liquid compressor from Pneumaticraft no longer believes that Firewater is a valid fuel. Other mods seem to, but not that one.     :(

**Comment by BBoldt** [comment]
well, whatever happened it will be fixed in Release 10


![](http://i.imgur.com/GeU3Gav.png)
