### ISSUE TITLE
Possible issue, possibly intentional - missing recipies

### ISSUE THREAD

**Issue by meradudd** [BBoldt/Unabridged#467]
I have noted that the following recipies are uncraftable (not just missing from NEI).  Not sure if this is intentional or an 'issue'.

Tropicraft - all tropical drink recipies other than the pina colada
Extra utilities - peaceful table, nether star (peaceful mode)
Remain in motion - Carriage Engine

**Comment by BBoldt** [comment]
Tropicraft drinks need to be made in the drink mixer: http://wiki.tropicraft.net/wiki/Drink_Mixer

Extra Utilities: Unabridged isn't really meant to be played in peaceful, those items are disabled.

Remain in Motion: https://github.com/planetguy32/RemainInMotion/issues/178#issuecomment-150318362

I've added some tooltips ingame explaining the tropical drinks and carriage engines.

**Comment by meradudd** [comment]
FYI, the translocator carriage recipe calls for a carriage motor, not a
carriage engine.  As such, they are un-craftable under the current setup,

The XU items being disabled is a real shame, but I respect your decision.

Thanks for the response and the hard work you do to keep this awesome pack
going.
