### ISSUE TITLE
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays throwed by EnderIOAddons

### ISSUE THREAD

**Issue by Axelandre42** [BBoldt/Unabridged#470]
Minecraft Unabridged crashes during the loading.

It's caused by EnderIOAddons...

There is the log :
http://paste.atlauncher.com/view/204cdc10

What's happening ?

Best regards,
Axelandre42 !

**Comment by GeoTerra** [comment]
It should be noted that I am getting the same error thrown by EnderIO Addons. This not a localized issue.

Log: http://pastebin.com/KcwfPyxq
(I would've used the paste service provided by the ATLauncher, however, my console doesn't show the full log)

This crash is preventing me from opening the pack at all. I have removed & reinstalled several times this morning, and have gotten the same crash. The pack worked fine the previous night. Optional mods selection has not changed.

**Comment by Axelandre42** [comment]
I found that :
https://github.com/HenryLoenwind/EnderIOAddons/issues/22
It's the matching issue in the EIO Addons' Issues Tracker.

**Comment by GeoTerra** [comment]
According to Henry, the fixed version appears to be live, so hopefully the pack author will update it soon.

**Comment by BBoldt** [comment]
this was fixed in 9a

https://www.reddit.com/r/MinecraftUnabridged/comments/3x5dgg/unabridged_release_9a_emergency_fix/
