### ISSUE TITLE
RWG Replacement

### ISSUE THREAD

**Issue by GeoTerra** [BBoldt/Unabridged#471]
Due to Ted (The author of the Fun, Realistic, and Old World Gen mods) having gone, seemingly, MIA and support for his mods having all but gone at present, I would like to propose that, at least, the Realistic World Gen mod be deprecated and replaced with its more-or-less successor, the "Realistic Terrain Gen" (RTG) mod by "WhichOnesPink" on the Minecraft Forums (http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-).

I was playing with this mod some in a separate instance (outside of ATLauncher), and the vistas it provides from a nearby Biomes o' Plenty Crag biome were spectacular, especially when combined with the Unity resource pack (the MCF thread does have a slideshow that shows off the Vanilla biomes under the influence of the RTG mod). RTG offers more robust mod support, specifically when it comes to biomes, I have had absolutely no issues using it (aside from too many Thaumcraft Obelisks, Hollows and Totems in the Plains biome I was in, but I believe that's more on Azanor's side & how he decides where to generate them). Thus far, I have, actually, had a fair bit of fun, trying to find a MFR Rubber Tree so that I could get started down that mod (and any other mod whose recipes require plastic sheets).

While RTG is in beta, I must say that it is a definite step up from the original (which was an alpha, I believe).

As for the conditions of including the mod in a pack, they do not deviate very far from the standard conditions.

Thank you for your time,
Best Regards,
Geo Terra

**Comment by BBoldt** [comment]
I will do this replacement, but not in R10.

Need to wait for this:

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1294659-climate-control-change-climate-zones-sizes-ocean?comment=963

OWG and FWG is getting removed due to unfixed bugs and no maintainer.

**Comment by BBoldt** [comment]
Sorry, have decided not to make the switch.

RTG is a mess. It's in a constant state of change and would be a nightmare to support. It's always needing some new dependency like BiomeTweaker or Climate Control that have the potential to mess up existing worlds.

Say what you will about RWG, but it's hardly given me any issues at all, and it still looks great despite not being updated in a while. In my opinion, the worlds generated with RWG actually look a bit better than ones generated with RTG.
