### ISSUE TITLE
Magical wood recipe giving too many items in return

### ISSUE THREAD

**Issue by jinkhya** [BBoldt/Unabridged#473]
Hello, when you craft magical wood from extra utilities it gives you 21 items instead of 1 (or sometimes 17 or 18, it seems to be either random or depending on the order your putting the items in the crafting table)
http://snag.gy/eCKFA.jpg

**Comment by okyriosy** [comment]
I think it's intended to give more than one, it depends on the enchanted books used.

**Comment by BBoldt** [comment]
@okyriosy is correct. The amount you get depends on what level books used.
