### ISSUE TITLE
Crimson plating infusion only gives 1

### ISSUE THREAD

**Issue by P3pp3rF1y** [BBoldt/Unabridged#474]
Crimson plating infusion (Tainted magic mod) should per Thaumonomicon give 16 plating when infusing 1 iron ingot and 4 blood droplets, but it only produces 1 plating. Not sure if this is an issue with the pack or the mod. 

This happens with unabridged 9b.

**Comment by BBoldt** [comment]
Tried it in R10 and it gave me 16.

Try again after the update is out.
