### ISSUE TITLE
CustomThings Ores - No Vanilla Furnace Recipes

### ISSUE THREAD

**Issue by SephirothWS** [BBoldt/Unabridged#475]
These ores don't function similarily to their "vanilla" counterparts where you can smelt them for a single ingot of their type. Yeah, the processing recipes for say a pulverizer and sag mill exists, but the basic vanilla functionality of smelting the ores for a single ingot doesn't exist. I'm not sure if this was intended or not.

**Comment by BBoldt** [comment]
That's strange! The custom ores are just oredicted to be the same thing as regular ores.

I'll try to get this fixed in R10

**Comment by SephirothWS** [comment]
I don't believe vanilla uses the ore dictionary since that is a minecraft forge thing...

**Comment by BBoldt** [comment]
Fixed in r10
