### ISSUE TITLE
Tinkers' Beheading doesn't work on Wither Skeletons

### ISSUE THREAD

**Issue by SephirothWS** [BBoldt/Unabridged#476]
I have a cleaver with 100% beheading (8x obsidian + ender pearl modifier) made completely out of magical wood so I have this from the get-go; and I went to farm wither skeletons in the nether for their skulls. Apparently 100% beheading means I need to kill about 100 skeletons or so before I get a single head.

Not sure if this is a Tinker's issue, or an Ender IO issue, or a combination of both, but I just can't put my finger on what is causing this to not properly work as intended.

Working as intended would mean I should get a skull per wither skeleton I kill with above cleaver.

**Comment by BBoldt** [comment]
not sure

https://dl.dropboxusercontent.com/u/134976541/ShareX/2016-01/2016-01-11_00-42-50.mp4
