### ISSUE TITLE
Smelting Yellorium in Tinkers requires 1000mb per ingot

### ISSUE THREAD

**Issue by dredhorse** [BBoldt/Unabridged#477]
Smelting Yellorium in the Tinkers smeltery requires 1000mb per ingot, smelting an ingot produces 144 mb.

Running 9.0 with the hotfix, so don't know if 9.0a fixes it.

**Comment by dredhorse** [comment]
update to the issue... it requires 1000mb per ingot for casting, sorry for not being clear

**Comment by BBoldt** [comment]
Fixed and fixed:

![](http://i.imgur.com/87vYhfZ.png)

![](http://i.imgur.com/ryicJ3i.png)

![](http://i.imgur.com/ryicJ3i.png)

**Comment by BBoldt** [comment]
In release 10.
