### ISSUE TITLE
Bound Pick needs mining level adjustment

### ISSUE THREAD

**Issue by BBoldt** [BBoldt/Unabridged#480]
"BBoldt it seems like the bound pick still has the same problem it had last version. It can technically 'mine' stuff like diamond ore, but it isn't being given the proper mining level. If I mine a piece of diamond ore it will break that block at the speed the pick would normally, but the block would not drop any diamonds on break. Is it a simple iguana tweaks config change to fix this?" - whizard_dragon

**Comment by whizarddragon** [comment]
You should do a check on all of the bound tools. Ran into a situation today where I couldn't use my bound axe. Oddly enough JABBA barrels have a required mining level of copper for the axe to break them.
