### ISSUE TITLE
Upgrade 9b to 10 leaves old EnderIOAddons

### ISSUE THREAD

**Issue by Skar78** [BBoldt/Unabridged#483]
Hi,

Tested on 2 different PCs, each upgrading from 9b to 10 via ATLauncher.

First start-up failed because FML notices  EnderIOAddons-1.7.10-2.3.0.421 and 422 remained in the mod folder.

After deleting manually 421 everything fine.

**Comment by BBoldt** [comment]
Sounds like an issue with atlauncher.

When an update happens, the entire mod folder gets deleted, and the mods get readded.
