### ISSUE TITLE
Missing Recipe to convert Enderman Heads from HQE and Iguanatweeks to Ender IO

### ISSUE THREAD

**Issue by dredhorse** [BBoldt/Unabridged#491]
Atm you can only convert from EnderIO => HQW => IguanaTweeks.

EnderIO needs some Enderman Heads though for crafting. Also I'm only gathering HQE Heads in my Enderfarm via Extra Utilities and Storage Drawers.

So a recipe to convert to Ender IO Enderman Heads would be nice

**Comment by BBoldt** [comment]
this PR should fix it once I get around to accepting it: https://github.com/BBoldt/Unabridged/pull/487
