### ISSUE TITLE
Aether Companion Crash

### ISSUE THREAD

**Issue by Timiryazev** [BBoldt/Unabridged#492]
Game crashes whenever player has Aether II companion "Fleeting Stone" equipped.
Looks like a potionID overflow issue.
[crash-2016-02-23_10.57.24-client.txt](https://github.com/BBoldt/Unabridged/files/143257/crash-2016-02-23_10.57.24-client.txt)

**Comment by BBoldt** [comment]
there are so many mods using potions that it was out of potion IDs

Had to add this mod: http://minecraft.curseforge.com/projects/extended-potions

Fixed in v12.
