### ISSUE TITLE
Some Tinkers materials not available?

### ISSUE THREAD

**Issue by lavaheart** [BBoldt/Unabridged#493]
I can't make Slime rods or Paper toolbindings. I think it's because they're not on the list that shows up when you hold shift over the patterns. 

![oq03peq](https://cloud.githubusercontent.com/assets/14857914/13793707/6e8f5fde-eab5-11e5-95ad-0e3b0208768d.png)
![zlb2lsk](https://cloud.githubusercontent.com/assets/14857914/13793708/6e971134-eab5-11e5-8ee4-a2538ebfe936.png)

sorry the images are kinda big.

**Comment by NdMSnIpEz** [comment]
The mod that makes this change is Iguana's Tweaks. The mod makes it so you can't make certain parts with certain materials to balance the mod. This isn't a bug. Not only that, but this is the wrong mod github either way. You can change the configs of the mod if you really want to use a paper tough binding.

**Comment by NdMSnIpEz** [comment]
Iguana's Tweaks adds this functionality. It's meant to be like that.

**Comment by BBoldt** [comment]
Sick of getting bug reports for this and it's confusing for those who have never played with Iguana Tweaks. Part restrictions will be disabled in v12!
