### ISSUE TITLE
Thermal Smeltery Auto Caster Uncraftable

### ISSUE THREAD

**Issue by SephirothWS** [BBoldt/Unabridged#494]
So I am currently trying to craft the Auto-Caster from Thermal Smeltery.

![Image](http://i.imgur.com/B9ihQS6.png)

My problem is when I go to pull this item out of the crafting table, it reverts this, and puts the crafting materials right back into the crafting table, disallowing me to craft this block.

---------

**e**: Oh, I see https://github.com/Drullkus/ThermalSmeltery/issues/29 is a thing. ... Guess @Drullkus will need to fix this on his end..

**Comment by Drullkus** [comment]
Huh? Oh. Crap.
