### ISSUE TITLE
Ender IO & Enhanced Portals Recipe Conflict

### ISSUE THREAD

**Issue by SephirothWS** [BBoldt/Unabridged#496]
![Image 1](http://i.imgur.com/Q4Z8UEw.png)
![Image 2](http://i.imgur.com/0nlYaKe.png)

Its impossible to craft the Weather Obelisk from Ender IO due to this recipe conflict.

**Comment by BBoldt** [comment]
http://wiki.enderio.com/Weather_Crystal
![](http://i.imgur.com/Koa47w8.png)

Fixed in v12.
