### ISSUE TITLE
Nether Quartz is extremely rare

### ISSUE THREAD

**Issue by arovin** [BBoldt/Unabridged#497]
**Issue Description:**
Nether quartz is not generating in the nether. Only spawning in "hell" biome.

In the vanilla.json file under cofh/world/ the section "quartz" change "biomeRestriction": "none",

this fixes the issues allowing nether quartz  to spawn in the BoP nether biomes. 

**Steps to Reproduce:**

**Crash report or log (uploaded to gist.github.com or pastebin.com):**

**Comment by BBoldt** [comment]
Fixed in r13
