### ISSUE TITLE
Server chat is hidden between dimentions

### ISSUE THREAD

**Issue by arovin** [BBoldt/Unabridged#498]
**Issue Description:**
By default on release 12 server chat is hidden for playing in other dimensions. So if player one is in the nether and all other players are in the over world no one (except ops) can see players ones chat.

To fix this in asielib.cfg set B:enableChatTweaks=false
**Steps to Reproduce:**

**Crash report or log (uploaded to gist.github.com or pastebin.com):**

**Comment by BBoldt** [comment]
Fixed in R13
