### ISSUE TITLE
Mekanism Turbine Crash

### ISSUE THREAD

**Issue by neersighted** [BBoldt/Unabridged#499]
**Issue Description:**
The Mekanism Industrial Turbine can cause a rendering crash, leaving users unable to log in as long as the turbine is formed and in a nearby chunk.
**Steps to Reproduce:**
Open the Industrial Turbine UI, and drop an item from your inventory.
You will disconnect from the server, and upon logging in again will crash almost immediately, with a fuschia or light blue solid screen.
**Crash report or log (uploaded to gist.github.com or pastebin.com):**
Crash log from original report (I can attach my own crash log if needed)
https://github.com/aidancbrady/Mekanism/issues/3239

**Comment by neersighted** [comment]
(the latest version of Mekanism resolves this with a simple null check)

**Comment by BBoldt** [comment]
Fixed in R13
