### ISSUE TITLE
Maple Woods Biome ID clash with galacticraft biome ID.

### ISSUE THREAD

**Issue by pmytilin1984** [BBoldt/Unabridged#500]
biome ID of Maple Woods in config/biomesoplenty/id.cfg is 104
biome ID of asteroids in config/Galacticraft/world.conf is 102+2=104

changed base value of world.conf to 160, a range with ample room which wasn't covered in id.cfg. and config/RWG.cfg and twilight forest. Didn't check other worldgen mods, but I think these values should be fine for most setups.

Didn't check for further clashes with other worlgen mods.

**Steps to Reproduce:**
enter Maple Woods biome 100% reproducible (RTW enabled, but that is most probably besides the point)

affects hostile mob spawning in the area. zombies e.g. spawn as their space counterparts, space suit and everything.

**Crash report or log (uploaded to gist.github.com or pastebin.com): Not applicable

**Comment by BBoldt** [comment]
Fixed in R13
