### ISSUE TITLE
Mekanism infusion factories accept no automated imports

### ISSUE THREAD

**Issue by stephanstross** [BBoldt/Unabridged#503]
I just attempted to automatically port compressed redstone from mekanism into the basic and advanced infusion factories. Their input sides were correctly set with the configurator item (Specifically, the purple Extra option), and I attempted to use vanilla hoppers, Applied Energistics export buses and interfaces, and mekanism's own logistical sorter. None managed to push any items at all into the factories. I assume the same issue exists with both the basic infuser, and the elite factory.

**Comment by BBoldt** [comment]
Working for me, probably was fixed in one of the Mekanism updates without me doing anything:

http://i.imgur.com/57VkO9y.png
http://i.imgur.com/7EFsLxw.png
http://i.imgur.com/YxCWZ2d.png
http://i.imgur.com/YaFgNON.png
