### ISSUE TITLE
Agricraft sprinklers server crash 

### ISSUE THREAD

**Issue by knoxhack** [BBoldt/Unabridged#505]
**Issue Description:**
Some players from my server can't get back to their base they keep crashing.
The crash report does't say what block is doing that.
They said it starting crashing while placing an Agricraft sprinkler.
I tried deleting a all sprinklers from that location with world edit but there was none.

My server is also using KCauldron (1.7.10-1614.200)

here is the crash report:
https://gist.github.com/knoxhack/9b5f448e2b63e38dcd345bc7ee7a00e3

**Comment by SephirothWS** [comment]
```
java.lang.ArrayIndexOutOfBoundsException: 3
	at biomesoplenty.common.blocks.BlockBOPNewFarmland.func_149691_a(BlockBOPNewFarmland.java:75)
```

Talks about a Biomes O Plenty farmland style block. Is that location in say a Garden or Origin Valley biome?

**Comment by knoxhack** [comment]
Nothing, now I have even more players in corrupted chunks, i got like 5 players already that can't get to their base on ny server, is not KCauldron issue, I tried without it and the same thing, is a client crash.

**Comment by BBoldt** [comment]
Fastcraft and KCauldron are incompatible.

Remove fastcraft.
