### ISSUE TITLE
Getting Timed out.

### ISSUE THREAD

**Issue by PastaBiceps** [BBoldt/Unabridged#507]
Hello there!

A friend of mine has set up her own minecraft unabridged server, which is currently running the R13 version.
Lots of people are able to join without a single problem, except for me. I can join for a few seconds/minutes, but then suddenly I get disconnected with the message "timed out".
Everyone is so hyped about this pack, and i'm not able to play it in multiplayer..
However, single player works just fine.

Here is the log, and I get disconnected at line 350: http://paste.atlauncher.com/view/f916aff5

I have tried updating my java (already is the newest version to my knowledge), tried downgrading java.
Reinstalled the pack multiple times, completely deleted ATlauncher.
Tried playing it without any optional mods.
She cleared my whole player from the server, so I would join as if I was a new person. Didn't help.
So I decided to check out other servers, see if the same problem occurs there. And it indeed did, got timed out there as well.
Disabled my firewall, even the firewall in my router.. Still no result, so I enabled them again.

Then I tried different modpacks as RR3, also on a server she owns, but not a single problem with that. Can play for hours on there.

Is there anything you could do for me, or have a suggestion of what I could possibly do?

PS: If you need any additional information, please let me know!

**Comment by BBoldt** [comment]
Hmm.

``` [14/8/2016 16:43:23 PM] [Client thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.network.PacketSimple:handleClientSide:814]: Cannot create directory %minecraftDir%/assets/temp! ```

Maybe there is a write problem? Do you have full permissions for the folder you have the pack installed to?

If that doesn't work, send me your full log. Located in

```
\Unabridged\logs\fml-client-latest.log
```

**Comment by PastaBiceps** [comment]
I have full permission over that folder (every folder for as far as I know).
https://gist.github.com/PastaBiceps/bb78b807ab8e329744de9c9f5a652462
Here is the log, hopefully you can get something out of this

**Comment by PastaBiceps** [comment]
It has been 2 days and sadly still could not find a good solution for this.. Sometimes I can play for a minute or 2 but then I am getting timed out, does not matter what I am doing. Wether it be walking, opening my inventory, looking around, doing nothing.. just happens randomly it seems. And the weird thing is is that it's on multiple servers happening to me, not just one..

**Comment by BBoldt** [comment]
Very strange. Unfortunately this seems like something specific to you, as I haven't gotten any other reports about it.

I'm not sure what is different about your setup that is causing this..

Maybe get a log from a server owner that shows the portion where you disconnect.

**Comment by PastaBiceps** [comment]
Allright managed to fix it after all :)
It had to do with my wifi setup.
When i'm on the 5ghz frequency of my router, I could play for a bit but then got disconnected.
When I'm on the 2.4ghz frequency of my router, I can play as long as I want without any trouble.
Not sure why this is happening, since the 5ghz one is way way faster... and have no problem whatsoever with any other modpack when playing on a server.

Btw about the log from a server owner; it just looks as if i disconnected from the game to them, as if I clicked the disconnect button.

Anyways, glad it's resolved, and hopefully you're able to do something with this information. 👍

**Comment by BBoldt** [comment]
Glad you got it figured out! There isn't really anything I can do with this info, but the issue may help people in the future if they ever encounter anything similar.

Thanks for the update!
