### ISSUE TITLE
[1.10.2] AppleCore might be unnecessary

### ISSUE THREAD

**Issue by squeek502** [BBoldt/Unabridged#514]
Hey, just happened to notice that you're currently including AppleCore v2.0.0 but (unless I'm missing something) you're not including anything that uses the AppleCore API. Starting with v2.0.0, I split the HUD features (food value tooltips, saturation visualization, etc) of the mod into a separate standalone mod called [AppleSkin](https://minecraft.curseforge.com/projects/appleskin), so if that's why you were including AppleCore, you should use AppleSkin instead.

(you can see what features AppleCore provides [here](https://github.com/squeek502/AppleCore/wiki/AppleCore-features))

**Comment by BBoldt** [comment]
Oh, right. I have both applecore and appleskin, forgot to remove applecore.

Thanks for the heads up!

**Comment by squeek502** [comment]
Ah, alright; AppleSkin wasn't/isn't showing up in this list for me: https://minecraft.curseforge.com/projects/unabridged/relations/dependencies

**Comment by BBoldt** [comment]
I might have forgotten to add it...

**Comment by BBoldt** [comment]
I did. I'll fix it for the next version.

**Comment by BBoldt** [comment]
This was fixed in a.3
