### ISSUE TITLE
Pistronics 2 rod recipe issue

### ISSUE THREAD

**Issue by noah13245678** [BBoldt/Unabridged#516]
**Minecraft version:** 1.7.10

**Unabridged version:** R13

**Issue Description:** NEI shows it takes 2 rod parts to craft a rod (from Pistronics), but in an actual crafting table it only takes 1, which essentially lets you craft unlimited rods. Screenshot: http://imgur.com/a/NGivI

**Steps to Reproduce:** Put a rod part in any crafting table

**Comment by adegarimore** [comment]
Only way I can fix this is if the mod author decides to roll out an update to fix it. Highly unlikely seeing that the last update was over a year ago.
