### ISSUE TITLE
Inconsistent Thaumcraft Aspects Across Items of Same Kind

### ISSUE THREAD

**Issue by Aedda** [BBoldt/Unabridged#517]
**Minecraft version:** 1.7.10

**Unabridged version:** R.13

**Issue Description:** Some mod versions of vanilla items do not have expected Thaumcraft Aspects for item type.

**Steps to Reproduce:** spoiler 

 

didn't work lol

**Comment by BBoldt** [comment]
http://i.imgur.com/j9L8G6b.png
