### ISSUE TITLE
Double doors won't close

### ISSUE THREAD

**Issue by adegarimore** [BBoldt/Unabridged#518]
Minecraft version: 1.10.2

Unabridged version: Unabridged A.3

Issue Description: Vanilla double doors won't close unless you shift+Right click

Steps to Reproduce: 
  -Place down 2 oak doors next to each other.
  -Open doors and observe fancy double door behavior
  -Attempt to close doors
  -Fail

May be a problem between Quark and Malisis doors?

**Comment by adegarimore** [comment]
In case it makes any difference, this is happeing on the server. Not tested in SP

**Comment by BBoldt** [comment]
fixed in a4
