### ISSUE TITLE
Item scroller not working

### ISSUE THREAD

**Issue by adegarimore** [BBoldt/Unabridged#519]
Minecraft version:1.10.2

**Unabridged version: Unabridged A.3

Issue Description: 2 mods are trying to add the item scrolling ability. it's not working out well

Steps to Reproduce:
  -Put a stack items in a chest
  -Hover mouse over items
  -Use scroll wheel to attempt to move items into your inventory
  -Fail

Fix: Change line 3 in MouseTweaks.cfg to WheelTweak=0

**Comment by BBoldt** [comment]
fixed in a4, I added itemscroller mod forgetting about mousetweaks
