### ISSUE TITLE
[1.10.2] Stacked pumpkins equp to head slot when shift-clicked

### ISSUE THREAD

**Issue by krumble1** [BBoldt/Unabridged#520]
**Minecraft version:**
1.10.2

**Unabridged version:**
a.3

**Issue Description:**
I can shift-click multiple stacked pumpkins into my head item slot, but dropping a stack only places one item into the slot. This might extend to other wearable items but I haven't tested it.

**Steps to Reproduce:**
Shift-click a stack of pumpkins with an empty head slot.

**Comment by BBoldt** [comment]
Vanilla bug: https://bugs.mojang.com/browse/MC-7222

Closing because not relevant. If anyone else sees this issue in the future at least they know what's up.
