### ISSUE TITLE
Opencomputers diamond chip

### ISSUE THREAD

**Issue by Thrinador** [BBoldt/Unabridged#523]
The recipe for the opencomputers diamond chip gets blocks by enhanced portals diamond nugget. There is no other way to get diamond chips.

**Comment by adegarimore** [comment]
it's not finished yet but here's my take on some new OC recipes.
[OCrecipes.zip](https://github.com/BBoldt/Unabridged/files/458486/OCrecipes.zip)

Edit: Round 2
I'm calling this finished. Hope you like it :) I made sure there were no recipe conflicts with other mods. Tried to make the recipes simple (and a little less expensive) to encourage people to use the mod.
[OCrecipes.zip](https://github.com/BBoldt/Unabridged/files/465214/OCrecipes.zip)

**Comment by alyeakitty** [comment]
Fixed diamond chip recipe in user.recipes with:
chipDiamond {
  type: shapeless
  input: nuggetDiamond
  output: 1}

**Comment by BBoldt** [comment]
#556
