### ISSUE TITLE
Nether Quartz is missing from R13, config issue

### ISSUE THREAD

**Issue by Aedda** [BBoldt/Unabridged#524]
Due to an error in the ore gen config for R13 Quartz cannot generate in the Nether. The rare cases where it is appearing is actually a bug.

To resolve this the **cofh/world/Vanilla.json** file needs to be changed to reflect the following:

``` text
    "quartz": {
        "template": "uniform",
        "block": "quartz_ore",
        "material": "minecraft:netherrack",
        "clusterSize": 13,
        "numClusters": 16,
        "minHeight": 10,
        "maxHeight": 118,
        "retrogen": "true",
        "biomeRestriction": "whitelist",
        "biomes": [
            {"type": "dictionary", "entry": "NETHER"}
        ],
        "dimensionRestriction": "none",
        "dimensions": []
    }
```

**Comment by adegarimore** [comment]
The only place I could find it was around nether hives. I assume that forestry adds that, and that it's not a bug. Thanks for the updated config :+1:

**Comment by BBoldt** [comment]
#525
