### ISSUE TITLE
Armorer's Workshop Mannequin Crash

### ISSUE THREAD

**Issue by SephirothWS** [BBoldt/Unabridged#528]
**Minecraft version:** 1.7.10

**Unabridged version:** R13a

**Issue Description:** Dedicated server crash upon placing an Armorer's Workshop Mannequin

**Steps to Reproduce:** 
1. Craft a Mannequin from Armorer's Workshop
2. Place Mannequin into the world.
3. ???
4. Profit.

**Crash report or log (uploaded to gist.github.com or pastebin.com):**
https://gist.github.com/SephirothWS/ee4369f0babcdd84471dffb20b0ca252

**Comment by adegarimore** [comment]
Fixed in R14
