### ISSUE TITLE
Client Console Spam after disconnecting from server

### ISSUE THREAD

**Issue by SephirothWS** [BBoldt/Unabridged#530]
**Minecraft version:** 1.10.2

**Unabridged version:** a4

**Issue Description:** Client console spam upon disconnecting from server and returning to the title screen. Doesn't seem to affect anything, aside from leaving a ghost on the server until the client is completely closed out.

**Steps to Reproduce:** I performed the following steps after clearing out my logs folder for a fresh set of logs.
1. Launch Unabridged.
2. Connect to multiplayer server. (This _does NOT_ apply to a Single Player world!)
3. ... Disconnect from said multiplayer server.
4. Watch the magic happen in your client console.
5. ???
6. Profit.

**Crash report or log (uploaded to gist.github.com or pastebin.com):**

https://gist.github.com/SephirothWS/d963d9debe842faeb2526eed1c77b20f

... Truncated files once again, but the full logs are there, this gist has _**3 log files**_ attached to it.

**Comment by 4rz0** [comment]
After disconnecting, as long as the client is open, the console gets spammed with https://gist.github.com/4rz0/f2277ebf992328edf14505a9f9db2f3c

**Comment by SephirothWS** [comment]
Just tested, this client log spam does _NOT_ occur after saving and quitting from a single-player world. This only happens after disconnecting from a multiplayer server.

**Comment by SephirothWS** [comment]
This problem has been resolved with the latest version of Abridged.
