### ISSUE TITLE
JEI Color Search breaks searching for items

### ISSUE THREAD

**Issue by SephirothWS** [BBoldt/Unabridged#531]
**Minecraft version:** 1.10.2

**Unabridged version:** a4

**Issue Description:** JEI Color Search breaks searching for items. For some reason, the option in JEI for color searching is enabled by default in a4, allowing for the player to find blocks by color. While this is quite a neat feature in & of itself, it _does_ have a problem understanding normal search terms.

![With Color Search ON](https://i.imgur.com/HkfAZIu.png)
The above search was performed with Color Search ON.

![With Color Search OFF](https://i.imgur.com/EU5ykya.png)
This is with Color Search OFF.

**Steps to Reproduce:**
1. Launch Unabridged.
2. Enter a single-player world, or connect to a server.
3. Open your inventory.
4. Click the Wrench at the far bottom right and check what "Enable Color Search" is set to.
5. If it isn't enabled, enable it.
6. Click done to apply the settings.
7. Search for "Jetpack" in JEI.
8. Notice no results.
9. ???
10. Profit.

**Crash report or log (uploaded to gist.github.com or pastebin.com):**
N/A

**Comment by BBoldt** [comment]
fixed a while ago
