### ISSUE TITLE
Add Sand & Tinker's Stone Torches to GravelMiner

### ISSUE THREAD

**Issue by SephirothWS** [BBoldt/Unabridged#533]
**Minecraft version:** 1.10.2

**Unabridged version:** a4

**Issue Description:** I love how GravelMiner eats away gravel blocks that would fall on your face. ... But digging underneath sand is a whole 'nother story. ... I've created a [Pull Request](https://github.com/BBoldt/Unabridged/pull/532) adding this functionality.

**Steps to Reproduce:** N/A

**Crash report or log (uploaded to gist.github.com or pastebin.com):** N/A

**Comment by 4rz0** [comment]
I'm actually for removing GravelMiner completely.

It's part of vanilla gameplay to learn to be careful and not dig below sand/gravel and get suffocated.
It's also pretty annoying if you _actually want_ to cause gravel/sand to fall down by digging away its last supporting block.

**Comment by SephirothWS** [comment]
@4rz0 Depending on your server, if they're using the configs shipped with Unabridged 1.10.2 or Abridged 1.10.2, GravelMiner is "Opt-in". If you want your annoying gravel falling on your face, then simply remove it from your client and you can have gravel falling down on your face.

**Comment by 4rz0** [comment]
Oh, awesome! Works :D
