### ISSUE TITLE
[1.7.10] Suggestion: Adding NEID mod to pack

### ISSUE THREAD

**Issue by kociara81** [BBoldt/Unabridged#535]
Not Enough IDs it's a mod that expand hardcoded ids limit. Now it mostly expands item id. 

It can have problems with some mods but I think it's worth testing.

Link to mod:
https://mods.curse.com/mc-mods/minecraft/235107-notenoughids

**Comment by BBoldt** [comment]
Causes some strange issues and crashes. Too hacky to add.
