### ISSUE TITLE
[1.7.10] Suggestion: Adding No more recipes conflict mod to pack

### ISSUE THREAD

**Issue by kociara81** [BBoldt/Unabridged#536]
This mod allows multiple recipes sharing the same crafting layout to be crafted, the player being able to choose using either a cycle button, or a new key binding.

It's great solution for those annoying recipe conflicts and work with most mods.

Link to mod:
https://mods.curse.com/mc-mods/minecraft/238123-stimmedcow-nomorerecipeconflict

**Comment by BBoldt** [comment]
No, would rather fix the recipe conflicts. There aren't that many that I know of currently, if you know of any, report them.
