### ISSUE TITLE
Fireworks possibly causing crash.

### ISSUE THREAD

**Issue by zevric** [BBoldt/Unabridged#537]
**Minecraft version:**1.7.10

**Unabridged version:**Release 13a

**Issue Description:**The gifts from aether 2 cause players visuals to freeze but the game itself is still going. I'm able to move them from the area but that entire area is messed up due to this.

**Steps to Reproduce:**Open the aether 2 gifts until it launches fireworks.

**Crash report or log (uploaded to gist.github.com or pastebin.com):**

**Comment by BBoldt** [comment]
Switching to Aether Legacy in next release.
