### ISSUE TITLE
[1.10.2][Abridged][Request] Hud clock

### ISSUE THREAD

**Issue by Aedda** [BBoldt/Unabridged#538]
I'm so used to telling what time it is in Unabridged by looking at the hud, if we could get a like hud for Abridged, time, general info stuff. that would be super!

**Comment by 4rz0** [comment]
I can recommend [InGame Info XML](https://minecraft.curseforge.com/projects/ingame-info-xml) for that.
Very configurable to not only show RL time but also other stuff as well.

Disadvantage: Requires another mod to work ([LunatriusCore](https://minecraft.curseforge.com/projects/lunatriuscore)).

**Comment by BBoldt** [comment]
I'm definitely going to use InGame Info XML, I already have it setup from when I used it in Pioneers.

I have it setup to look exactly like the hud in 1.7.10 Unabridged, that was being provided by Zyin's then.

**Comment by BBoldt** [comment]
Added in Beta 3
