### ISSUE TITLE
Jumping on farmland makes the client unhappy

### ISSUE THREAD

**Issue by Aedda** [BBoldt/Unabridged#539]
Occasionally jumping on a tilled farm land to turn it back into dirt results in becoming stuck in the block for a random amount of time (the effect is like a missing chunk, the sky gets dark and the camera becomes bouncy) until it fixes itself or the block is broken. This results in the falling crunch sound but no damage. Could be a vanilla thing, haven't played enough 1.10.2 to know.

**Comment by 4rz0** [comment]
Never had this before on any of my 1.10 instances, must be some mod-related issue.
I'll investigate on that this evening.

**Comment by Aedda** [comment]
I've further tested this and found it happens both in single player and server. 3/4 times jumping on a piece of farmland will cause the player to become stuck in that block. Any method that pulls the player up (jetpack, etc.) frees them as does breaking the block. Attempting to move may or may not resolve it.

**Comment by BBoldt** [comment]
This is a weird one.

**Comment by adegarimore** [comment]
This is a vanilla bug. It occurs even when forge is removed

**Comment by 4rz0** [comment]
https://bugs.mojang.com/browse/MC-104259
