### ISSUE TITLE
Nether portal weirdness

### ISSUE THREAD

**Issue by adegarimore** [BBoldt/Unabridged#540]
Version: Minecraft 1.10.2 - Abridged B1

Issue Description: Sometimes, Going through a nether portal (from the nether to the overworld) causes a server crash. On server reload, you are somewhere kinda not really close to spawn (usually underground) with no nether poratal to be seen.

Steps to Reproduce:  Go into the nether, Try to come out.

Crash report: https://unascribed.com/t/d71d05db.txt

**Comment by 4rz0** [comment]
I'll test that in a few hours as well.

**Comment by BBoldt** [comment]
Has this happened again @unascribed?

Guessing it may be something to do with nether portal fix mod.

**Comment by exaskye** [comment]
Not sure. I don't think so?

**Comment by adegarimore** [comment]
https://minecraft.curseforge.com/projects/netherportalfix/issues/1
