### ISSUE TITLE
[1.10.2][Abridged][Request] Automated Redstone Mod

### ISSUE THREAD

**Issue by Aedda** [BBoldt/Unabridged#545]
Since there is nothing for managing, routing, and compacting redstone in this pack consider adding this. No one but weirdos like the vanilla redstone and there is soooooo much that can be improved with a good redstone mod.

**Comment by BBoldt** [comment]
Waiting on Super Circuit Maker to be released. Until then, you have EnderIO redstone conduits and some things from RFtools and Extra Utilities.
