### ISSUE TITLE
Mod Request: Easy Breeding

### ISSUE THREAD

**Issue by adegarimore** [BBoldt/Unabridged#547]
Version: Minecraft 1.10.2 - Abridged B1

[Easy Breeding](https://mods.curse.com/mc-mods/minecraft/236045-easy-breeding#t1:other-downloads) adds a small feature that was in Better Than Wolves, and it should pair well with Better with mods.

**Comment by BBoldt** [comment]
https://github.com/BeetoGuy/BetterWithMods/issues/51

**Comment by BBoldt** [comment]
Closing since it will be in the mod. If you're looking for anything else from BTW, be patient, or request it on the Better With Mods github page.
