### ISSUE TITLE
[1.7.10][Unabridged][R13a][SMP] Armourers-Workshop crash involving Mannequins

### ISSUE THREAD

**Issue by Aedda** [BBoldt/Unabridged#548]
This is being reported third hand. Xydryhn reported that a server they were on crashed and has severely corrupted briefly after using a Mannequin from Armourers-Workshop. No crashlog is available.

I looked into the issue and it appears to be known and resolved, in the version of Armourers-Workshop (0.39.1) immediately following the one in the pack (0.39.0)

`Fixed: Dedicated server crash when updating mannequin slots.`

and in 0.39.2:

`Fixed NPE crash when placing a mannequin.`

The current version as of this issue is 0.39.6 and includes a number of other important bug fixes and changes between 0.39.2 and current.

**Comment by Xydryhn** [comment]
The corruption was localized to the one chunk the Mannequin itself was located at, the server worked fine normally until the chunks in question were loaded. We attempted to use world edit to fix the problem but to no avail. The final fix came in tracking down the specific region file and deleting that manually via FTP.

**Comment by Aedda** [comment]
Duplicate of issue #528 sorry about that, hopefully still helpful.

**Comment by BBoldt** [comment]
yep, duplicate 😛
