### ISSUE TITLE
Mod Request: Chat Flow

### ISSUE THREAD

**Issue by adegarimore** [BBoldt/Unabridged#549]
Version: Minecraft 1.10.2 - Abridged B1

[ChatFlow](https://minecraft.curseforge.com/projects/chatflow) by Vazkii
A simple mod that changes how some chat messages are displayed.

1.10.2 Abridged
- [ ] Better With Mods
- [ ] Blood Magic
- [x] Vanilla
- [x] CoPo
- [x] Mekanism
- [ ] Persistant Bits
- [x] Psi

1.7.10 Unabridged
- [x] Vanilla
- [x] Mekanism
- [x] Carpenter's Blocks

**Comment by BBoldt** [comment]
Only if you can figure out a good way for me to set up some nice defaults that everyone can use without configuring it themselves.

**Comment by adegarimore** [comment]
https://github.com/Vazkii/ChatFlow/issues/8

**Comment by adegarimore** [comment]
Added in Beta: 6

**Comment by adegarimore** [comment]
Adding to Unabridged

**Comment by adegarimore** [comment]
Seems abandoned
