### ISSUE TITLE
[1.10.2][Abridged][Request] Streams + Farseek API

### ISSUE THREAD

**Issue by cHaOZZoNE** [BBoldt/Unabridged#551]
Basically a mod that adds "real" flowing streams to the game. I have added it on B.2 and it does not seem to cause any issues with either BoP or other preexisting mods in the rudimentary testing I have done. FPS wise it also seems to neither cause issues during world gen nor during regular play.

Only thing is that their post links to a wrong version of the API which does not work with 1.10.2.

[MCForum post](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2346379-streams-real-flowing-rivers)

![2016-09-25_22 40 12](https://cloud.githubusercontent.com/assets/6075069/18818124/c1ff7366-8371-11e6-84aa-17d28db9069d.png)
![2016-09-25_22 42 25](https://cloud.githubusercontent.com/assets/6075069/18818126/c20068de-8371-11e6-9112-466d9850cd66.png)
![2016-09-25_22 39 58](https://cloud.githubusercontent.com/assets/6075069/18818125/c200552e-8371-11e6-9ff5-b31546ab1908.png)

All screens are from the default version as of 25.09 (B.2)

**Comment by cHaOZZoNE** [comment]
Only thing to add is that it would likely profit from another terrain generation mod which plays a bit more with the height-level (i.e. RTG or similar) as the water flowing down a slope looks nicer than the flat rivers (compare screens 1 and 2).

**Comment by BBoldt** [comment]
While minimal, it does impact world generation time. I would like to limit mods that do that, at least for Abridged. I may include RTG + Streams in Unabridged 1.10 whenever I get to that.
