### ISSUE TITLE
Mod Request: Ender FlowerGirls

### ISSUE THREAD

**Issue by adegarimore** [BBoldt/Unabridged#555]
Version: Minecraft 1.10.2 - Abridged B2

Issue Description:
Endermen... I mean Endergirls seem to only pick up grass blocks and dirt blocks.

Steps to Reproduce:
- Spawn in an Endergirl.
- (optional) Place down some pink flamingos.
- Wait for her to pick something up.
- Observe that it is not a flower
- Ragequit

Crash report: none

Fix:
[This Mod](https://minecraft.curseforge.com/projects/ender-flowergirls) seems to fix Mojang's major enderma...err endergirl oversight.

**Comment by BBoldt** [comment]
I'm not sure I like the idea of messing with vanilla mechanics like this. I will agree that enderman can be annoying, but i'm not sure forced gender reassignment surgery is the right choice.

**Comment by BBoldt** [comment]
I'll decide based on the response to this request: https://minecraft.curseforge.com/projects/ender-flowergirls?comment=8

**Comment by adegarimore** [comment]
Looks like there's not going to be a config for this. I may consider adding this in the future, but for now, we'll leave it out.
