### ISSUE TITLE
[1.10.2][Abridged][B3] Random mobs missing their textures

### ISSUE THREAD

**Issue by Aedda** [BBoldt/Unabridged#557]
Upgraded to Beta 3 and now random mobs have no texture, they are solid white.

https://i.imgur.com/qHRSCYd.png

https://i.imgur.com/kWLZfPP.png

Steps to reproduce, update to Beta 3.

If no one else is having this issue or it cannot be reproduced Curse did throw an error while updating and I can try a fresh profile.

Curse error for the curious:
Profile Error, Curse encountered a problem during this operation [updating to beta3]. Error of type 'Curse.Radium.InstallManagement.InstallTaskFailedException' was thrown.

**Comment by BBoldt** [comment]
Was Journeymap
