### ISSUE TITLE
[1.10.2][Abridged][B3][Request] Disable EnderThing chests from breaking

### ISSUE THREAD

**Issue by Aedda** [BBoldt/Unabridged#558]
EnderThing as you know adds color coded ender chests like Ender Storage used to provide. However unlike Ender Storage EnderThing chests cannot be moved, they only return a piece of obsidian as a result. In Beta 3 they were updated with the option of allowing picking up the chest without breaking it, I would very much request this be enabled (or rather that breakage be disabled). The chests are not very expensive to begin with and all it does is add hassle to the process of using them.

There is the argument that Robots could use them to dump inventory into but I think this is very unlikely to significantly change balance since Robots are already complicated to make and all it does is save some energy.

Thank you

**Comment by BBoldt** [comment]
Fixed in Beta 4
