### ISSUE TITLE
[1.10.2][Abridged][B3] RFTools Storage Modules only accept Oak Chests

### ISSUE THREAD

**Issue by Aedda** [BBoldt/Unabridged#559]
When creating the Storage Modules for RFTools Modular Storage the recipe only accepts Oak Chests, would be helpful if this were corrected.

P.S.- Consider maybe adding a recipe to turn any chest into an Oak Chest.

**Comment by adegarimore** [comment]
https://github.com/McJty/RFTools/issues/859

**Comment by adegarimore** [comment]
I'll have a temporary fix in the next version. I cant make all the recipes accept any chest. just some of the recipes.

**Comment by adegarimore** [comment]
Partially fixed in Beta: 6

**Comment by adegarimore** [comment]
Partially fixed. This is all I can do.
