### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by djstar25** [BBoldt/Unabridged#560]
This isn't truly an issue more of a suggestion and I didn't know were to post it. PLEASE ADD IN MAGICAL CROPS!?!

**Comment by adegarimore** [comment]
Check out agricraft. It's already in the pack and you can grow a lot of things including metals, redstone, glowstone, gems, botania petals etc...

**Comment by djstar25** [comment]
No closed

**Comment by djstar25** [comment]
Yes but theres certain armor and tools in magical crops as well as it's not
as tedious as agricraft

**Comment by gr8pefish** [comment]
Feel free to add it yourself to your own instance. Additionally, please stop spamming this post, thank you!
