### ISSUE TITLE
Abridged B4: Mekanism Machines below Forestry Farm

### ISSUE THREAD

**Issue by Skar78** [BBoldt/Unabridged#561]
Hi,

My Mekanism maschines (metallurgic infuser, enrichment chamber all the way up to digital miner) occasional show up an erratic render behavior when i place them close to my forestry farm (below it, one height lvl below the hatch and below the farm area. 

They suddenly turn 90° as a render issue and turn back after i opened their inventory.  I tested if this is related to the resource pack but its not, and it is reproducible for me as in if i place the block again close to the farm it happens again.

**Comment by adegarimore** [comment]
can you take a screenshot of your setup? I cant seem to replicate this on my end.

**Comment by Skar78** [comment]
Here you go: https://postimg.org/gallery/2p6h8mnk4/

The file names of the screenshots are time stamps so the machine is turning multiple times by 90° back and forth within a few seconds.

(The original issue was posted as beta 4, now its beta 5.1 this is a single player world.)

**Comment by adegarimore** [comment]
Looks like forestry changed some weird things going on between the farm block and Mekanism. I'm going to close this on the next update and assume it's fixed. Let me know if you are still having a problem.

**Comment by Skar78** [comment]
If I dont forget about it (no idea when the update is due) I will check it and report back.

**Comment by adegarimore** [comment]
Update is due in the next few days (if not today)

**Comment by Skar78** [comment]
Just an update: This happens also in Hermitpack 1.4. 

Although there I did not use a Forestry farm but a "space controller" from RFTools. Everything was fine for many many hours until I decided to duplicate the building (39x39 factory hall). As soon as I set up the space controller and configured the space the mekanism factorys showed the same behavior as within the Forestry farm. 

So relatively save to say it is not a mod pack specific issue.

**Comment by Skar78** [comment]
The issue was closed so not sure if this is still pen.

https://github.com/aidancbrady/Mekanism/issues/3977

**Comment by DietmarKrause** [comment]
same problem with wind mills and enderio farming station with dark oak wood trees about 10 Blocks away: https://github.com/aidancbrady/Mekanism/issues/3977

**Comment by BBoldt** [comment]
1.10 Unabridged/Abridged discontinued.
