### ISSUE TITLE
Correlated Potentialistics

### ISSUE THREAD

**Issue by Pellesaxon** [BBoldt/Unabridged#562]
Hello, I am playing on b4 of abridged Abridged and Correlated Potentialistics is bugged and needs a update! I would also like to see RS or AE2 instead of Correlated Potentialistics because thay are much more advanced. With other words the modpack really needs a update.

**Comment by adegarimore** [comment]
I do not plan on removing CoPo or replacing it with any other mod. If you are experiencing a bug with CoPo, please report it with the following format so I can attempt to fix it.

**Minecraft version:**

**Unabridged or Abridged version:**

**Issue Description:**

**Steps to Reproduce:**

**Crash report or log (uploaded to gist.github.com or pastebin.com):**

**Comment by Pellesaxon** [comment]
It is fixed in a newer version of the mod! That's why a said it needs to update!

**Comment by exaskye** [comment]
Abridged is running the latest version of CoPo, 2.0.0-alpha2.

So if it really is bugged and needs an update, /you/ are out of date, not the modpack.

You also have yet to say ~~what version of Abridged you're running and~~ what the issue you're having is.

**Comment by FiveEYZ** [comment]
i think he ment that CoPo2 needs to be updated

https://github.com/SpongePowered/SpongeForge/issues/1027
we need https://github.com/elytra/Correlated/commit/d4c0ce8dbcb6ea799e04b21a4843a5920456a9ca

**Comment by exaskye** [comment]
That commit hasn't made it into a released build yet, since I've been short on time.
