### ISSUE TITLE
Fix Oregen Duplicates

### ISSUE THREAD

**Issue by adegarimore** [BBoldt/Unabridged#564]
- [ ] IE, Mek, and poor Railcraft Copper
Maybe more??

**Comment by BBoldt** [comment]
IE copper should be disabled already

https://github.com/elytra/Unabridged/blob/1.10.2-Abridged/config/ImmersiveEngineering.cfg#L303

**Comment by DeGariless** [comment]
Well that's odd because I found some ie copper in my test world. I just
generated the world last night.
>
>

**Comment by adegarimore** [comment]
Poor copper ore
https://github.com/CovertJaguar/Railcraft/issues/1023

**Comment by adegarimore** [comment]
accidentally got an old save that I deleted instead of generating a new world.
