### ISSUE TITLE
Can't craft tool forge

### ISSUE THREAD

**Issue by Techtronik** [BBoldt/Unabridged#569]
**Minecraft version:**
1.10.2

**Unabridged or Abridged version:**
5.1

**Issue Description:**
Tool forge recipe won't come up in jei. It's craftable but you just can't bring up the recipe.

**Steps to Reproduce:**
attempt to open the jei recipe viewer for tool forges via hotkey or ~right~ left-click

**Crash report or log (uploaded to gist.github.com or pastebin.com):**
n/a

**Comment by adegarimore** [comment]
https://github.com/SlimeKnights/TinkersConstruct/issues/2539

**Comment by adegarimore** [comment]
Fixed in Beta: 6
