### ISSUE TITLE
Milk Bucket Missing

### ISSUE THREAD

**Issue by Seathes** [BBoldt/Unabridged#570]
**Minecraft version: 1.7.10**

**Unabridged or Abridged version: Unabridged ver. 13b**

**Issue Description: Item [Milk Bucket:335] is missing. Cannot craft cake without milk bucket.**

**Steps to Reproduce: Not listed in NEI, cannot craft. Milk+Bucket->Skyroot Milk Bucket: 4262. Cannot craft cake with Skyroot Milk Bucket.**

**Crash report or log (uploaded to gist.github.com or pastebin.com): N/A**

**Comment by adegarimore** [comment]
I think this is fixed in the next update... No promises though.

**Comment by BBoldt** [comment]
Can confirm it is no longer happening in recent versions.
