### ISSUE TITLE
[Bug][Abridged 1.10] Sound engine crashes randomly

### ISSUE THREAD

**Issue by Techtronik** [BBoldt/Unabridged#575]
**Minecraft version:**
1.10.2

**Unabridged or Abridged version:**
Abridged Beta.6

**Issue Description:**
The sound engine crashes after a seemingly random interval. it doesn't effect gameplay other than having no sound. This wasn't occurring a couple weeks ago, just suddenly started happening and i can't find a fix for it.

It doesn't crash the client itself, just stops all game sounds from playing until i restart the client. all sounds outside the minecraft client work fine.

**Steps to Reproduce:**
Launch the pack, play for about an hour or two. that's all i'm doing. If it helps, i first noticed it when i was fighting my 4th or 5th Wither boss and the sound just suddenly cut out.

**Crash report or log (uploaded to gist.github.com or pastebin.com):**
http://pastebin.com/Hy6Nv7hA

**Comment by adegarimore** [comment]
For now, you can remove the mod "sound filters". If you still have a problem after removing it, let me know. Thanks

**Comment by Techtronik** [comment]
I've been playing for over an hour and the sound hasn't quit yet so i think removing that mod has fixed the issue. thanks.
