### ISSUE TITLE
[1.7.10] Suggestion: Update Armourer's Workshop to newer version

### ISSUE THREAD

**Issue by kociara81** [BBoldt/Unabridged#576]
**Minecraft version:*1.7.10

**Unabridged or Abridged version:**

**Issue Description:* Newer version of this mod added new feature (wings) and many fixes (mostly for Mannequin and doll crashes).

**Steps to Reproduce:**

**Crash report or log (uploaded to gist.github.com or pastebin.com):**

**Comment by adegarimore** [comment]
https://github.com/elytra/Unabridged/issues/573
