### ISSUE TITLE
Glitchy Mekanism jetpack enchantment aura

### ISSUE THREAD

**Issue by CrestedPeak9** [BBoldt/Unabridged#582]
**Minecraft version:** 1.7.10

**Unabridged or Abridged version:** 13b

**Issue Description:** After a Mekanism armored jetpack is enchanted, its aura contains glitchy textures that are very visible to both the player wearing it and other players.

**Steps to Reproduce:** Enchant a Mekanism armored jetpack (we used an enchantment book in an anvil) and wear it. The aura should start flashing odd colours.

**Crash report or log (uploaded to gist.github.com or pastebin.com):** None.
![screenshot 1](https://cloud.githubusercontent.com/assets/13196632/21419246/87cd3d56-c861-11e6-86db-841a3ae34617.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/13196632/21419247/87d6404a-c861-11e6-9fce-a997d9147615.png)
![screenshot 3](https://cloud.githubusercontent.com/assets/13196632/21419249/8866451e-c861-11e6-9284-52077672295a.png)
![screenshot 4](https://cloud.githubusercontent.com/assets/13196632/21419250/8894f7c4-c861-11e6-8ae1-b9f3689d16e8.png)
![screenshot 5](https://cloud.githubusercontent.com/assets/13196632/21419248/87e713f2-c861-11e6-863e-0391b6844911.png)

**Comment by adegarimore** [comment]
Not sure there's anything I can do about this one. because this is purely cosmetic, I will not be putting effort into fixing this one. Thanks for the report though. I really appreciate all the feedback I can get.
