### ISSUE TITLE
Tails Mod not working

### ISSUE THREAD

**Issue by Ki11erRabbit** [BBoldt/Unabridged#583]
Minecraft version: 1.7.10

Unabridged or Abridged version: Unabridged

Issue Description: For some reason I cannot use the tails mod but other players on the same server can set a tail for themselves.

Steps to Reproduce: No steps

Crash report or log (uploaded to gist.github.com or pastebin.com): N/A

**Comment by adegarimore** [comment]
Sanity check:
Are you sure you installed the Tails mod on your client?

**Comment by Ki11erRabbit** [comment]
Well some how it fixed itself.
