### ISSUE TITLE
Fluxduct Type Interconnectivity Issue

### ISSUE THREAD

**Issue by ChronomegaIV** [BBoldt/Unabridged#584]
**Minecraft version:** 
1.7.10

**Unabridged or Abridged version:** 
Unabridged 13b 
Manually updated Armourer's Workshop to fix mannequin issue
Added Veinminer

**Issue Description:**
Trying to connect multiple types of fluxduct won't allow power through properly.
I have Redstone Energy Fluxduct traveling from an Advanced Generators steam generator into my mob grinder room. To conserve space, the redstone fluxduct connects to a Flux-Plated fluiduct, then back into a set of redstone fluxducts again, then back into another flux-plated fluiduct. If I click on the flux plated fluiduct with a wrench, little spurts of power connect through.

I created a test world to repeat the steps and ran into a somewhat similar issue. It did carry the power through the fluxduct, but never fully charged them.

**Steps to Reproduce:**
Picture Attached:
![2016-12-23_00 15 37](https://cloud.githubusercontent.com/assets/10465659/21449747/48884e62-c8a5-11e6-8ec4-8301153c78c5.png)
![2016-12-23_00 15 42](https://cloud.githubusercontent.com/assets/10465659/21449745/48862394-c8a5-11e6-9c33-7f0818821f9d.png)
![2016-12-23_00 15 49](https://cloud.githubusercontent.com/assets/10465659/21449746/4887ef76-c8a5-11e6-8a89-252ab3e61c38.png)

**Comment by adegarimore** [comment]
I'm guessing that your grinder is sucking up all the power? I cannot reproduce this. I have used all of the TE pipes and have tried running fluid through the flux-plated one. I cannot find any funny business.
![](http://i.imgur.com/nselQOE.png)

**Comment by exaskye** [comment]
This is a side-effect of how Thermal Dynamics is designed, you're limited to the transfer rate of the Flux-Plated Fluiduct (which is quite low) - you can connect to it multiple times to transfer more. If you transfer enough to match the rate of the fluxduct on the  other side it should work better.

I could be wrong, I haven't played 1.7.10 in a while.

**Comment by adegarimore** [comment]
Can confirm. This is my understanding of how all "RF networks" work. They are limited at the point of connection independently from each other. Each time you use a duct with a different transfer rate, it makes its own new "RF network"
