### ISSUE TITLE
Ferrous ingot and block recipe issue

### ISSUE THREAD

**Issue by adegarimore** [BBoldt/Unabridged#585]
**Minecraft version:** 1.7.10

**Unabridged or Abridged version:** Unabridged

**Issue Description:** 9 Ferrous ingots craft into a "Decorate Nickel Block" when playing on a server. NEI says it should craft into Ferrous block. Decorate Nickel Block is not able to be crafted back into ingots. This issue only occurs on the server side.

**Comment by BBoldt** [comment]
Ferrous and Nickel are the same thing..

**Comment by DeGariless** [comment]
Should have been more specific. Updated OP.

**Comment by BBoldt** [comment]
ah

**Comment by adegarimore** [comment]
Will make a script to fix it and will oreDict Decorate Nickel Block

**Comment by adegarimore** [comment]
Fixed in R14
