### ISSUE TITLE
 Mekanism Flame Thrower Breaks World (server crash) on Hitting Sugarcane :(

### ISSUE THREAD

**Issue by EmoBubbleGum** [BBoldt/Unabridged#586]
-->
**Minecraft version:**
 1.7.10

**Unabridged or Abridged version:**

 R13b

**Issue Description:**

So I shot the flamethrower on the setting "Inferno" at a piece of sugarcane, while messing around with it. Then my server crashed and every time i try to load up my character (where the flame is still trying to hit the sugarcane?) it crashes again.
I figured it was a buggy smelting recipe, but sugarcane has none. Here is the pastebin of the initial crash log. http://pastebin.com/PWJ9dK5r
Here is the second pastebin from when I tried to log back in, after turning the server back on. http://pastebin.com/YVTR3MqG

**Steps to Reproduce:**

Shoot sugarcane with the Mekanism flamethrower, on the inferno setting. (and possibly the heat setting too?)

**Crash report or log (uploaded to gist.github.com or pastebin.com):**

Crash on shot: http://pastebin.com/PWJ9dK5r
Crash after trying to go back in game after turning the server back on: http://pastebin.com/YVTR3MqG

**Comment by BBoldt** [comment]
Open your player.dat file with NBTexplorer and try removing the flamethrower from the inventory slot it was in.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/1262665-nbtexplorer-nbt-editor-for-windows-and-mac

**Comment by EmoBubbleGum** [comment]
Thanks, I will possibly try that shortly. Do you have any ideas for a permanent solution?

**Comment by EmoBubbleGum** [comment]
I double checked, and it is easily recreatable in solo mode. I hope it is fixed in the next update, because it can be quite world breaking.

**Comment by EmoBubbleGum** [comment]
So for any who have this problem, it can be fixed by deleting the chunk the problem is in. Such as with NBTExplorer. Though, this is still a serious issue that the people who organize the modpack should attempt to fix in the next iteration.

**Comment by adegarimore** [comment]
I'll do my best to get it fixed for the next update. I have a few theories on how to fix it. Wish me luck and thanks for the report :)

**Comment by adegarimore** [comment]
1.7.10 Mekanism has been abandoned. Unfortunately, there is nothing I can do short of removing the recipie for the flamethrower. I suggest removing the recipe with minetweaker if you are playing on a server.
