### ISSUE TITLE
Mod Request: Thaumic Tinkerer

### ISSUE THREAD

**Issue by Zekken01** [BBoldt/Unabridged#587]
Hey, I want to suggest that you add the mod [Thaumic Tinkerer](https://minecraft.curseforge.com/projects/thaumic-tinkerer) I know a lot of people (*Including me*) on a server that upset because it's not in the pack so that's why I'm asking you to add it.

**Comment by adegarimore** [comment]
I'm Sorry. I will mostly be doing bug fixes for this pack and trying to focus more of my time toward the newer 1.10.2 Abridged pack. that will hopefully turn into the newer 1.11 Unabridged pack. Mod additions are now closed for unabridged.
