### ISSUE TITLE
Iguana Tinker Tweaks Config Resets itself

### ISSUE THREAD

**Issue by EmoBubbleGum** [BBoldt/Unabridged#588]
**Minecraft version:**

1.2.10

**Unabridged or Abridged version:**

13b

**Issue Description:**

I have been trying to edit the main config and drastically change some of the level options and max levels. But the config file resets to default on it's own seemingly at random.

**Steps to Reproduce:**

Hard to say, it seems to reset randomly.

**Crash report or log (uploaded to gist.github.com or pastebin.com):**

N/A

**Comment by EmoBubbleGum** [comment]
So if I change the level settings almost at all it resets them on server restart.

**Comment by adegarimore** [comment]
With some mods, config files get overwritten when you stop the server/close your game. Usually this happens with mods that you can configure from in-game. I haven't tested this, but my guess is that you need to stop your server/close your game before you edit the config files.

**Comment by adegarimore** [comment]
it's generally good practice not to modify the config files while your game is running unless there is some sort of in-game "reload config" command.

**Comment by EmoBubbleGum** [comment]
It happens when ever I turn the server back on. If it doesn't like the values I put in. For instance if I set it to get modifiers on tools at level 1 2 3 5 7 9, it works. If I set it to 1 3 5 6 7, it doesn't. The numbers can't have a gap and then not have a gap after.

**Comment by adegarimore** [comment]
Sounds like it might be an issue with the mod itself. Because it's not a high priority bug, and because I'm currently focusing on Unabridged 1.10, it might be a while before I'm able to look into it.

**Comment by BBoldt** [comment]
Probably can't be fixed 1.7 iguana is pretty dead, and I'm not planning on changing level options for Unabridged 3, I'll consider doing it for future versions though. But on 1.16 I would probably have Tetra instead of Tcon. Still, probably a mod that could change mining values.
