### ISSUE TITLE
NEI crash

### ISSUE THREAD

**Issue by Oreo12** [BBoldt/Unabridged#589]
**Minecraft version:** 1.7.10

**Unabridged or Abridged version:** Unabridged

**Issue Description:** Crashing upon looking up recipes in NEI

**Steps to Reproduce:** Just look at any recipe in NEI

**Crash report or log (uploaded to gist.github.com or pastebin.com):**http://pastebin.com/wJmbW31k

**Comment by jbdman** [comment]
This is caused by an issue with NEI Integrations I believe. If you change the B: "Fluid Registry"=true to B: "Fluid Registry"=false, it no longer crashes on recipe lookup. Just a quick fix, there should be a more permanent way to fix this, I'm just not sure what it would be.

**Comment by Exopandora** [comment]
you need to build a new version of tonius' nei integration (development branch on github) that fixed this bug
https://github.com/Tonius/NEI-Integration
EDIT: Even with the patch the game crashes

**Comment by Exopandora** [comment]
I guess some registered fluids dont have a proper id set

**Comment by BBoldt** [comment]
Fluid registry is set to false in recent versions.
