### ISSUE TITLE
Portal Gun crashes

### ISSUE THREAD

**Issue by CartoonishVillain** [BBoldt/Unabridged#590]

**Comment by lionmaiden** [comment]
Portal guns are just one of the items that I put on the black list on my server. They, like you said, glitch and cause to many problems. Great mod but not for a server. Thanks for the info about transporting entities.

**Comment by adegarimore** [comment]
I'm going with lionmaiden here. Portal guns have kinda known to be glitchy. Cool mod though. I don't think I'll be making any attempt to fix because the last time this mod was updated was 2015
