### ISSUE TITLE
Redo OreGen

### ISSUE THREAD

**Issue by adegarimore** [BBoldt/Unabridged#592]
**Minecraft version:**

**Unabridged or Abridged version:**

**Issue Description:**

**Steps to Reproduce:**

**Crash report or log (uploaded to gist.github.com or pastebin.com):**

**Comment by Skar78** [comment]
This is in regards of Alpha 5? As i am drowning in TE copper and cant find lapis for the love of god.

(Did not find lapis at the level mentioned by NEI but at ~30ish in an extreme hill biome)

**Comment by adegarimore** [comment]
This is in reguards to probably most of alpha.dont listen to NEI. I need to fix that.

**Comment by adegarimore** [comment]
Also. Lapis and redstone generate is very very tall veins that usually reach from  bedrock to near the surface.

**Comment by adegarimore** [comment]
Not really sure why I opened this. there's not really a "fix". just kindof a general TODO I guess.
