### ISSUE TITLE
TOO MANY STICKS

### ISSUE THREAD

**Issue by BBoldt** [BBoldt/Unabridged#593]
**Minecraft version:**
1.10.2
**Unabridged or Abridged version:**
a.7
**Issue Description:**
Too many sticks lmao
![](http://i.imgur.com/d54Cl81.png)

**Steps to Reproduce:**
Walk around, pick up sticks.
**Crash report or log (uploaded to gist.github.com or pastebin.com):**

**Comment by adegarimore** [comment]
Fixed in A8
