### ISSUE TITLE
Rocks and shit behave strangely

### ISSUE THREAD

**Issue by BBoldt** [BBoldt/Unabridged#594]
**Minecraft version:**
1.10.2
**Unabridged or Abridged version:**
a7
**Issue Description:**
Stone needs to be broken twice, cobblestone and dirt fall like gravel, dirt-like objects can't be stacked more than a few high without falling over.
**Steps to Reproduce:**
Try to play and be annoyed by having to break stone twice and having cobble try to murder you by falling on your head.
**Crash report or log (uploaded to gist.github.com or pastebin.com):**

**Comment by adegarimore** [comment]
That's WTF's mod.

**Comment by BBoldt** [comment]
yeah, may want to disable a lot of the non cosmetic stuff

**Comment by adegarimore** [comment]
Will do

**Comment by BBoldt** [comment]
Also, consider removing the mod if it's too intrusive and not configurable enough.

**Comment by BBoldt** [comment]
lol mining ores makes the ground crumble around you, very disconcerting

**Comment by adegarimore** [comment]
Mod is very configuratable :)

**Comment by adegarimore** [comment]
Fixed in A8
