### ISSUE TITLE
Wrong leaves

### ISSUE THREAD

**Issue by adegarimore** [BBoldt/Unabridged#596]
Some RecurrentComplex oak trees have Acacia leaves

**Comment by Skar78** [comment]
Why do we want/need Recurrent Complex? I always feel this does not really add anything.

**Comment by BBoldt** [comment]
The exploration aspect it adds is the main reason it's been kept.

Also, I always had plans to make custom worldgen structures and spawn them in with RC, never got around to it. 

Also, it includes some amazing tools behind the scenes that would be a shame not to use a bit.

**Comment by exaskye** [comment]
Plus those giant quartz floating things it generates are pretty awesome, lets you skip a bunch of nether exploring :P

**Comment by Skar78** [comment]
Is there no better mod for exploring? I am literally never like "oh lets look for a rc structure" and after knowing most of them its just "bleh" every desert with a potential desert temple or a rogue dungeon motivates me more to explore.

While we are at the topic of exploring, nether got super boring in unabridged. just go there for a blaze spawner and once for the tic metals till you dont need them anymore... Think needs some spicing up.

**Comment by adegarimore** [comment]
I plan on adding nether ores, I just haven't gotten to yet.

**Comment by Skar78** [comment]
As a principle I always like all world gen changes to be in early - so you dont have to reset the world to have latest world gen and also have mid/later game testing instead of 20 start overs.

**Comment by BBoldt** [comment]
We are in alpha testing at the moment, don't get too attached to anything.

Also, in the exploration department we also have Natura back, for the first time in Unabridged since 1.6.4, that makes the nether look a lot nicer.

**Comment by Skar78** [comment]
The only thing i care about exploring is either a) find a beautiful place to call home, b) get some stuff to shortcut shit or c) test how op my gear is (fun) - so rc offers nothing in those 3 regards for me and natura...well at least i am not aware of it.

**Comment by BBoldt** [comment]
I beg to differ, RC offers things in both the A, B, and C categories you described.

A) A beautiful place to call home. There have been many times where i've found something generated by Recurrent Complex that looks amazing that I end up moving into. The original object ends up inspiring my whole base built around it.

B) Get some stuff to shortcut shit. As @unascribed mentioned above, there are some structures that spawn in items you would only find in the nether, as well as rare ores sometimes. Also their chests are usually populated with useful items.

C) Test how op your gear is. Recurrent complex adds structures that contain spawners, making them function as mini dungeons. Good place to test your weapons and stuff.

**Comment by Skar78** [comment]
Accept the points, its just that I feel roguelike does all of that better. ...and somehow i feel too often bothered by the placement of those structures.

**Comment by adegarimore** [comment]
https://github.com/Ivorforce/RecurrentComplex/issues/166

**Comment by BBoldt** [comment]
1.10 Unabridged/Abridged discontinued.
