### ISSUE TITLE
Exploring Crashes Server

### ISSUE THREAD

**Issue by Skar78** [BBoldt/Unabridged#598]
**Unabridged A7**

**Issue Description:** Looks like certain chunks crash the server on generation.

Description: 
Exception generating new chunk java.lang.RuntimeException: NULL biome found when mapping volcanoes.

**Steps to Reproduce:**
Create world. If crash at spawn, delete world and create new one. 
Change gamemode to C, fly around till crash - voila.

**Crash report or log (uploaded to gist.github.com or pastebin.com):**
http://pastebin.com/hUzhajL4

**Comment by adegarimore** [comment]
Looks like I'm going to have to remove RTG for now. I'll add it back if/when it becomes more stable. I really love this mod, but I can't include it in a release if it's causing crashes :(

**Comment by BBoldt** [comment]
Just for posterity, it looks like the crash was caused because RTG does not have a biome dictionary entry set up for the volcano biome, thus natura exploded when it tried to grow a tree.

**Comment by adegarimore** [comment]
Fixed in A8
