### ISSUE TITLE
Ore generation needs documentation

### ISSUE THREAD

**Issue by adegarimore** [BBoldt/Unabridged#604]

**Comment by Skar78** [comment]
BBoldt once did like an unabridged book/guide. I think that approach is rather good - but i basically would just put a single static page of concept/promise of the pack,  the roe generation, if necessarily special settings/highlights and a credit. (This is based on the gigantic assumption that progression needs no explanation.)

**Comment by BBoldt** [comment]
See if you can find a way to add documentation with JEI "Description" tags.

Might require a custom mod, I could talk to some people about it.

**Comment by adegarimore** [comment]
You read my mind. I feel like there's a mod for that already, a way to add descriptions via mine tweaker.

**Comment by exaskye** [comment]
I once wrote an [entire XML based system to do this](https://github.com/unascribed/Farrago/blob/master/src/main/resources/assets/farrago/encyclopedia.xml).

If it looks good I can update it. The item name system is fairly complex and is [explained over here](https://github.com/unascribed/Farrago/blob/master/src/main/java/com/unascribed/farrago/FarragoMod.java#L1017-L1055).

**Comment by BBoldt** [comment]
1.10 Unabridged/Abridged discontinued.
