### ISSUE TITLE
crash on chest opening

### ISSUE THREAD

**Issue by Skar78** [BBoldt/Unabridged#605]
**Unabridged:** A8

**Issue Description:** Focused on exploring to see if previously issue was resolved in a freshly created BoP World.
Opened a Chest froman EvilCraft Envir. Controller Structure (Dungeon Chest loot?) noticed an item without texture but crashed before i could mouseover it.

**Steps to Reproduce:** Could not reproduce. After loading game again and opening the chest it might have been a lava charm that was not rendered. As I dont know if special snowflake crash or something useful i decide to upload the crash report despite not being able to reproduce for ppl who can make sense of it.

**Crash report or log (uploaded to gist.github.com or pastebin.com):** http://pastebin.com/zeh9BXkV

**Comment by Skar78** [comment]
After some thought not sure if thats not some other issue. Here another crash, did absolutley nothing ebsides flying around in creative mode on a fresh world looking for a spot for a test base.

http://pastebin.com/2W5HKdRT

**Comment by Skar78** [comment]
Exact same happened again: http://pastebin.com/MfdPXGa9

This time it was easier to remember the slot in the chest - i am 100% positive that the item is gone after reload.

**Comment by Skar78** [comment]
So, i did some more exploring with a9.1 and bop, quarks rtg and default world. did not crash once even tho i would estimate i opened 20+ envir controller chests.

**Comment by BBoldt** [comment]
1.10 Unabridged/Abridged discontinued.
