### ISSUE TITLE
Custom OreGen crash

### ISSUE THREAD

**Issue by Skar78** [BBoldt/Unabridged#606]
**Unabridged version:** A8

**Issue Description:** Crash to desktop.

**Steps to Reproduce:** Fly around

**Crash report or log (uploaded to gist.github.com or pastebin.com):**
http://pastebin.com/nEXF1KP1

**Comment by exaskye** [comment]
Looks like Pam's HarvestCraft is reaching out of already-created chunks and is triggering an infinite loop heuristic in CustomOreGen.

**Comment by adegarimore** [comment]
I have flown around soo much and opened so many chests. No crashes yet. Either I'm really lucky, or you're really unlucky.

**Comment by BBoldt** [comment]
1.10 Unabridged/Abridged discontinued.
