### ISSUE TITLE
Magnetized Flags Demagnetize Themselves (Update EnderIO Addons)

### ISSUE THREAD

**Issue by piepie62** [BBoldt/Unabridged#609]
**Minecraft version:**
1.7.10
**Unabridged or Abridged version:**
Unabridged R14
**Issue Description:**
Magnetized flags demagnetize themselves; fixed in EnderIO Addons v0.10.12
**Steps to Reproduce:**
Look at magnetized flag
**Crash report or log (uploaded to gist.github.com or pastebin.com):**

**Comment by BBoldt** [comment]
EIO Addons is being removed in next update, not because of this issue but it does solve it. 😛
