### ISSUE TITLE
Torch wallplacing going overboard

### ISSUE THREAD

**Issue by BBoldt** [BBoldt/Unabridged#610]
**Minecraft version:**1.10

**Unabridged or Abridged version:**B9

**Issue Description:** I right clicked this wall to place the cobblestone in my hand, and it took the torch out of my offhand and placed it on the wall. Happens when holding shift. Super annoying. Also sometimes happens when jumping.

**Steps to Reproduce:**

**Crash report or log (uploaded to gist.github.com or pastebin.com):**

**Comment by BBoldt** [comment]
Also sometimes happens when jumping.

**Comment by BBoldt** [comment]
.

**Comment by adegarimore** [comment]
I cant place a torch unless it's in my hand. Are you somehow using the old config file for client tweaks? "Right-Click Places Torch from Hotbar" should be set to false.

**Comment by hvdklauw** [comment]
Maybe too close too the wall so a whole block won't fit, then the offhand is automatically tried
