### ISSUE TITLE
[1.10.2][Unabridged][Beta 9.1] Extra Utilities 2 Transfer Node Recipe missing

### ISSUE THREAD

**Issue by hvdklauw** [BBoldt/Unabridged#613]
There is no recipe for the EU2 transfer node. Looks like the minetweaker script removes it and then readds it to allow any chest to be used (See #554). But I guess something broke in the readding.

Code in _Other.zs:
```
## Extra Utilities ##

# Oredicted transfer node
recipes.remove(<extrautils2:grocket>);
recipes.addShaped(<extrautils2:grocket> * 4, [[<ore:redstone>,    <extrautils2:pipe>, <ore:redstone>],
                                              [<ore:stone>, <ore:chestWood>,              <ore:stone>]]);
```

**Comment by BBoldt** [comment]
Unabridged 4 for 1.10.2 no longer supported.

Unabridged 6 coming soon™
