### ISSUE TITLE
Missing file from curse

### ISSUE THREAD

**Issue by Time6628** [BBoldt/Unabridged#614]
**Minecraft version:** 1.10.2

**Unabridged or Abridged version:** Beta 9.1

**Issue Description:** There's a mod from curse that is no longer on curse, so the pack won't download.

**Steps to Reproduce:**  Download the pack.

**Crash report or log (uploaded to gist.github.com or pastebin.com):** https://gist.github.com/Time6628/59f8c6b3a333b40413cb1ef0622e1857

**Comment by Abstention** [comment]
I'm having the **exact** same issue...

**Comment by BBoldt** [comment]
The 1.10.2 version has been split off and updated, this is no longer an issue.

https://minecraft.curseforge.com/projects/unabridged-iv
