### ISSUE TITLE
EnderIO Cobblestone framework crashing anyone in loaded chunk

### ISSUE THREAD

**Issue by ghost** [BBoldt/Unabridged#616]
**Minecraft version:**
1.7.10

**Unabridged or Abridged version:**
Unabridged Release 14

**Issue Description:**
I have an Ender IO cobblestone framework working with an octadic capacitor in order to produce bedrockium, but after I destroyed the auto crafter tier 3 from RFTools on top, it completely crashed my client and the client of anybody who gets within range of my loaded chunks. I've tried four times to get back online to try and see what's going on but every single time it crashes me to desktop. I'd perform a server restart but the other admins who are yet to give me console access aren't online right now, so there's nothing I can do for the time being. Will a server restart even fix anything, or do we need to do something more extreme? 

**Steps to Reproduce:**
Tried four times to reconnect, even had a friend approach my base and they crashed out as soon as the chunks loaded in. 

**Crash report or log (uploaded to gist.github.com or pastebin.com):**
https://pastebin.com/883MvkaN

I really hope there's something I can do

**Comment by BBoldt** [comment]
That mod is long abandoned so a bug report wont really help, but you can remove EnderIO Addons and that should fix your problem.

Only side effects will be the removal of EnderIO Addons blocks from the world, which shouldn't be a major issue as it doesn't really add all that many blocks.

**Comment by BBoldt** [comment]
EnderIO Addons removed in 3.18.

https://www.reddit.com/r/MinecraftUnabridged/comments/khe9qz/unabridged_315_318_new_ars_magica_2_ic2_classic/
