### ISSUE TITLE
Texture pack wont load - Sphax 

### ISSUE THREAD

**Issue by BBoldt** [BBoldt/Unabridged#620]
**Minecraft version:** 1.12.2

**Unabridged or Abridged version:** B.2

**Issue Description:** Texture pack wont load (Sphax http://bdcraft.net/purebdcraft-minecraft)

**Steps to Reproduce:** Try to load texture pack.

**Crash report or log (uploaded to gist.github.com or pastebin.com):** https://ghostbin.com/paste/z9cv3

**Comment by BBoldt** [comment]
@asiekierka The crash report mentions charset, but I don't know if it actually involves you or not yet

**Comment by asiekierka** [comment]
Seems to be BuildCraft/Charset interacting weirdly, possibly with a third mod involved?

**Comment by BBoldt** [comment]
Unabridged 5 now unsupported.
