### ISSUE TITLE
Thaumcraft biomes using RWG

### ISSUE THREAD

**Issue by MeVsTheVoices** [BBoldt/Unabridged#623]
**Minecraft version:**
1.7.10
**Unabridged or Abridged version:**
Release 15
**Issue Description:**
No thaumcraft biomes spawning while using Real World Generator to generate the world.
**Steps to Reproduce:**
Set world seed as RWG. Set thaumcraft biome generation settings to whatever. Create a new world.
**Crash report or log (uploaded to gist.github.com or pastebin.com):**
https://gist.github.com/MeVsTheVoices/a9d9fb6aa08fb9c1a917c068bc9a543a

**Comment by BBoldt** [comment]
RWG is getting removed in the next version. The version in unabridged is completely unfinished and got abandoned.
