### ISSUE TITLE
[1.12.2] [Unabridged III][B.3] - Symptom:Graphical Glitch - Cause: Mekanism/backtools interaction

### ISSUE THREAD

**Issue by ThePoshTux** [BBoldt/Unabridged#624]
**Minecraft version:**
1.12.2

**Unabridged or Abridged version:**
B.3 Twitch Launcher

**Issue Description:**
Inventory appears to be empty but items can still be moved. This issue has previously existed: https://github.com/aidancbrady/Mekanism/issues/1367

**Steps to Reproduce:**
Place Atomic disassembler in hotbar along with another tool, scroll along the hotbar and look in your inventory. (only occurs when "back tools" tries to load the disassembler onto the back)
For easier testing going into the 3rd person will show the state of the back. If the other tool becomes oversized and incorrectly orientated the inventory should be blank upon entering. Scrolling right to left across hotbar until reaching the right again makes the inventory reappear.

**Temporary fix**
Disable back tools mod, as "back tools" doesn't appear to have any item blacklist options.

**Future Fix**
If a config option to blacklist tools, in fact, does not exist in "backtools" then pester IChun to add one.

**Crash report or log (uploaded to gist.github.com or pastebin.com):**
https://pastebin.com/NNpzatky

**Comment by BBoldt** [comment]
Unabridged 5 for 1.12 is now unsupported.

Unabridged 6 for 1.16.4 coming soon™.
