### ISSUE TITLE
CD4017BE Library Missing

### ISSUE THREAD

**Issue by eawilhelm** [BBoldt/Unabridged#626]
**Minecraft version:** 1.12.2

**Unabridged or Abridged version:** Unabridged V

**Issue Description:** Just missing the Lib in Description for Modpack on Twitch. 

**Steps to Reproduce:** Install Modpack Unabridged V version B.4  and launch it.  You'll get an error.  
Easy Fix to just get the Lib missing and plop it in Mods Folder. :)

**Comment by BBoldt** [comment]
https://minecraft.curseforge.com/projects/unabridged-v/files/2692696
