### ISSUE TITLE
Game crashes when breaking tombstone

### ISSUE THREAD

**Issue by fluffybunny100** [BBoldt/Unabridged#628]
**Minecraft version:**
Minecraft 1.7.10
**Unabridged or Abridged version:**
1.7.10 reimagined Beta (b.17)
**Issue Description:**
Game crashes when breaking tombstone
**Steps to Reproduce:**
Game crashes when breaking tombstone
**Crash report or log (uploaded to gist.github.com or pastebin.com):**
[crash-2019-08-22_16.15.26-server.txt](https://github.com/elytra/Unabridged/files/3532291/crash-2019-08-22_16.15.26-server.txt)
Error Message:
Error: cpw.mods.fml.relauncher.ReflectionHelper$UnableToFindMethodException: java.lang.NoSuchMethodException: net.minecraft.client.multiplayer.PlayerControllerMP.k()

**Comment by BBoldt** [comment]
Not happening in my tests on 3.18.3.

**Comment by asiekierka** [comment]
This is the BugfixMod/BugPatch issue; the mod was removed and should be replaced by an alternative soon-ish.
