### ISSUE TITLE
Advertising/Managing/General Unabridged problem

### ISSUE THREAD

**Issue by Fuhrmaaj** [BBoldt/Unabridged#629]
OK, so I started up a new world the same way I always have, which is to pop open the AT Launcher. There are a ton of bugs and glitches, so I decide to start ripping apart the configs. 

* "Make sure you're on the latest version of the modpack."

Then I Google Unabridged and find b17, where I've been playing r15. There is no information on the Github or the subreddit about where you're supposed to get the most recent version of the pack. I saw someone report an issue with R16 on the subreddit, which is amazing because I still haven't find those files ANYWHERE online.

**Minecraft version:**
I get that it's been a long time since peak activity, and a lot of the contributors rotate in and out, but even when we're here we are all interested in different versions of the game. So then updates aren't really done.

**Issue Description:**
So the pack is hidden, only one version of Unabridged is updated at a time, and the contributors have lives.

**Proposed Solution**
- Update the subreddit to tell people which version of the pack is the most recent, and where to get the most recent version for each release. I can do that, but I'm not 100% sure I know where the pack is being distributed from anymore.

- We have a few groups of players who are really dedicated to Unabridged, and we don't all play on the same version. I think we should recruit a moderating/design team from people who keep coming back to this pack. Make sure that there is representation for each version of Unabridged (or at least 3 & 5, which seem the most active).

- Aggregate the passwords to everywhere the pack has presence (AT Launcher, Curseforge, Github, etc.), and give them to each member of this team. The goal of this is so that it increases the chance that someone is paying attention to Minecraft whenever a bug arises. As of right now, I am a moderator of the subreddit, but nothing else so the pack is dead in the water until someone comes back and sees me screaming into the void. I have to imagine that I'm not the first person who has encountered this problem.

- I would like to be one of the people who has access to update the pack and how it's distributed. I have contributed more than the stats here indicate. When I started, I didn't know how to use git so I would give updated configs directly to BBoldt. I would also talk with BBoldt about updates and mods and the like. I ran a server for Unabridged 3 from my computer for a couple years which allowed anybody to join, so I've met a lot of the people who play this pack. I only play Unabridged 3, and in fact, I have very limited experience past Minecraft 1.7.10, so I'd be completely focused on that. Curseforge says we're back in beta, so it would be nice to have someone testing and updating the pack.

I have a concussion, so I hope that this is legible and makes sense.

**Comment by BBoldt** [comment]
Agreed, I'll work on making things more clear, especially about what versions of the pack exist and were worked on last.

I like the design team idea, I don't know how to go about recruiting people for that though, maybe the subreddit? I know a few people but they've likely moved on. As of this posting the design team is now you and me.

**Comment by BBoldt** [comment]
The subreddit is updated with correct information, new discord server, twitter, and new release of Unabridged 3.18.3 on both ATLauncher and CurseForge.

Switched Unabridged to semantic versioning.
Unabridged 3.18.3 is Unabridged 3 for 1.7.10, Release 18, Hotfix 3.
Unabridged 5.4.1 is Unabridged 5 for 1.12.2, Release 4, Hotfix 1. (currently unsupported)

All future releases will follow semantic versioning to reduce confusion.

Unabridged 3 is currently the only supported version. Supported versions may change in the future. If I focus on anything next it will be Unabridged 6 for 1.16.4. Unabridged 4 & 5 were never really finished and I don't think they are worth more effort in their current state, they would need a big re-imagining.

I don't think we need to setup a team to maintain a 5 year old modpack, there isn't much to do or that can be done for it at this point. I am totally open to collaboration via pull requests or solving issues here on github. We can do things like add more compatibility between mods with crafttweaker scripts, further fine tuning the configs, and adding new content using existing tools in the pack. The 1.7.10 branch has  Unabridged 3 configs, scripts, and all additonal custom content here on Github.

**Links**
Twitter: https://twitter.com/bboldtabridged
Discord: https://discord.com/invite/wV3jFx7F2e
Reddit: http://www.reddit.com/r/MinecraftUnabridged/
Atlauncher: https://www.atlauncher.com/pack/MinecraftUnabridged
CurseForge: https://www.curseforge.com/minecraft/modpacks/unabridged-iii
