### ISSUE TITLE
U3 Game crashes every time a block is broken

### ISSUE THREAD

**Issue by Fuhrmaaj** [BBoldt/Unabridged#630]
**Minecraft version:** 1.7.10

**Unabridged or Abridged version:** b17 on CurseForge

**Issue Description:** Game crashes whenever you break a block

**Steps to Reproduce:** Make a new world, break anything. I noticed that some items that didn't get placed properly didn't crash the world, ie. it's not the item entity causing the problem. (I picked up poppies that worldgen tried to place on a sand block)

**Crash report or log (uploaded to gist.github.com or pastebin.com):** https://pastebin.com/bmfWpQ14

Also, this problem is over a year old. Two people have posted about it on the subreddit: https://www.reddit.com/r/MinecraftUnabridged/comments/b74qdx/1710_unabridged_iii_the_reimagining_updatebeta/

I manually removed the mod on my instance, and now the game works fine.

I did my own digging by accident before I downloaded b17 and found out that this is a known problem with the BugPatch mod. I'll post the mod's curseforge here, but look at the comments. It's a really common problem with this mod.:
https://www.curseforge.com/minecraft/mc-mods/bugpatch

Anyways, it looks to me as though the best thing we can do right now is to roll back to the BugfixMod, but I don't see a CurseForge page for it. The MCF post is here: https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1294346-bugfixmod-2-5-0-various-annoyances-fixed-boat

If my understanding is correct, the CurseForge launcher necessitates that the mod has a CurseForge page. If no alternative is found, it will probably be best to just remove the BugPatch mod.

**Comment by asiekierka** [comment]
There's a fix [here](https://github.com/deNULL/BugPatch/pull/1) - you could consider rebranding the mod and putting the rebranded version of CF (like BugPatch did to BugfixMod, I assume).

**Comment by Fuhrmaaj** [comment]
Hey asie, I'm glad you saw this. I'm not a programmer, I can only write simple programs in Javascript or C and I'm not good with git. Thank you for figuring this out, when I get some time I'll try to do that. Thank you so much!

**Comment by BBoldt** [comment]
BugfixMod is out of the pack for now, but I'll leave this open until @Fuhrmaaj or I rebrand it and post on CF with the fixes above. Would like to re-add it at some point.

Removed in 3.18:
https://www.reddit.com/r/MinecraftUnabridged/comments/khe9qz/unabridged_315_318_new_ars_magica_2_ic2_classic/

**Comment by asiekierka** [comment]
Regarding rebranding: Contacted williewillus; am working on something in that direction. Stay tuned!

**Comment by asiekierka** [comment]
https://github.com/asiekierka/FoamFix17/commit/b2b8da8a7af56c0ad8dabd7db9f99e49b9cbe460

Release "vaguely soon". MIT license.

**Comment by asiekierka** [comment]
https://www.curseforge.com/minecraft/mc-mods/foamfix-optimization-mod/files/3146426

Also available on charset.asie.pl. Merry Christmas.
