### ISSUE TITLE
Massive FPS drop when entering Labyrinth in the Aether.

### ISSUE THREAD

**Issue by UnderHandedJoe** [BBoldt/Unabridged#631]
Title says it all, evetime I go into a labyrinth in the Aether my FPS drops from 120 to 4 and its completely unplayable.

**Comment by Fuhrmaaj** [comment]
There are about 3 Aethers right now. Which version of minecraft and unabridged did this happen on?

**Comment by BBoldt** [comment]
I'm releasing a new version for 1.7.10 soon, and I'm switching to aether legacy. It's more complete and less buggy.

**Comment by BBoldt** [comment]
3.18.3 released on both CurseForge and ATLauncher, replaces Aether II with The Aether.

https://www.curseforge.com/minecraft/mc-mods/the-aether

A lot of other changes as well, may not be compatible with your current world:
https://www.reddit.com/r/MinecraftUnabridged/comments/khe9qz/unabridged_315_318_new_ars_magica_2_ic2_classic/
