### ISSUE TITLE
Game crashes on loadup with Curseforge

### ISSUE THREAD

**Issue by jonnierose** [BBoldt/Unabridged#634]
Minecraft version: 1.7.10

Unabridged III version: 3.18.3

Issue Description: Game crashes while trying to loadup, after completeing intializion I and attempting to enter II I think. 

Steps to Reproduce: download pack on curseforge and try to run

Crash report or log (uploaded to gist.github.com or pastebin.com):
(https://gist.github.com/jonnierose/c08b2ef7b69fba4356f44debcd4274a3#file-crash-2020-12-22_16-06-19-client-txt)

**Comment by BBoldt** [comment]
That version of Uplink has a bug with windows 7. Just remove uplink from your mods folder until I release the next update that includes a fix.

**Comment by jonnierose** [comment]
ok thankyou!
