### ISSUE TITLE
U3 Multiple mods generating Andesite, Diorite, and Granite.

### ISSUE THREAD

**Issue by Fuhrmaaj** [BBoldt/Unabridged#635]
**Minecraft version:** 1.7.10

**Unabridged or Abridged version:** 3.18.3

**Issue Description:** Both Chisel and UpToDateMod are generating these. I think UTDM should not be generating the rock because Chisel lets you do all the conversions. Maybe make it so UTDM rock can be converted using a chisel, or just make recipes to craft the unique blocks.

I think UTDM uniquely adds Polished Rock Stairs, Rock Slab block (made by putting one slab on another in the world, not crafted), Polished Rock Slab, Polished Rock Slab block,  (only checked for granite). I don't think if the textures are identical or not. It doesn't look like they're ore dict so that you can use any block, which seems to be intentional so you can craft blocks from each specific mod. I think that's fine.

**Comment by BBoldt** [comment]
I'm going to keep the UpToDateMod ones generating, and add them to chisel so they can be converted. The Chisel ones have gross textures lol.
