### ISSUE TITLE
Mod additions and updates for 3.18.4

### ISSUE THREAD

**Issue by BBoldt** [BBoldt/Unabridged#637]
- Uplink
- Foamfix
- Starminer (maybe)
- Tails (maybe)
- NEI gtnh
- Crafttweaker gtnh (potential distribution issues on CF)
- blood magic gtnh (potential distribution issues on CF)

thoughts anyone? anything else missing? @Fuhrmaaj

**Comment by BBoldt** [comment]
* Simple Harvest

**Comment by Fuhrmaaj** [comment]
Yeah, I think it looks good. I say ship it.

**Comment by BBoldt** [comment]
* Computronics
* AsieLib
* RedLogic (maybe)

**Comment by BBoldt** [comment]
* JointBlock (maybe)

**Comment by BBoldt** [comment]
* Mekanism Terralization

**Comment by BBoldt** [comment]
* Factorization

**Comment by BBoldt** [comment]
I might just save some of these for 3.19, for big mod additions at least.

**Comment by BBoldt** [comment]
* Clay Soldiers

**Comment by BBoldt** [comment]
* Dynamic Dynamos

**Comment by BBoldt** [comment]
* HexCraft?

**Comment by BBoldt** [comment]
* BeeBetterAtBees

**Comment by BBoldt** [comment]
continued in #656
