### ISSUE TITLE
phosphor recipies only partially in NEI

### ISSUE THREAD

**Issue by EmoBubbleGum** [BBoldt/Unabridged#646]
**Minecraft version:** (mc1.7.10)

**Unabridged or Abridged version:** Unabridged 3

**Issue Description:** phosphor recipes missing when checking to see its uses, but there when you check lava recipes

**Steps to Reproduce:** if you press U on phosphor to see recipes it can be used for, it doesn't show that it can be used with dirt/cobble/normal sand in the squeezer. however if you check the recipes to make lava, you see those options there.

**Comment by BBoldt** [comment]
No idea how to fix this one. It's either a bug in NEI or Forestry.

As a consolation prize for me not being able to fix it, I'm adding a new secret recipe!

![](https://i.imgur.com/XLyjlTh.png)

**Comment by EmoBubbleGum** [comment]
awesome, thanks lol
