### ISSUE TITLE
Disappearing items from IC2

### ISSUE THREAD

**Issue by Pandoras-end-network** [BBoldt/Unabridged#648]
**Minecraft version:**
1.7.10

**Unabridged or Abridged version:**
Unabridged 3.19.1

**Issue Description:**
Items are disappearing from IC2 machines. While there is nothing to pipe them out. Happens in both Singleplayer and on a server.
I also tested it on version 3.18.3 and the machines work normally there

**Steps to Reproduce:**

1. Place IC2 generator
2. Input coal in the bottom slot
3. Close generator inventory
4. Open generator inventory, and the coal is gone

**Crash report or log (uploaded to gist.github.com or pastebin.com):**

https://user-images.githubusercontent.com/74044802/104953307-6eaa8e00-59c6-11eb-8b97-3ff07fdb8a49.mp4

**Comment by EmoBubbleGum** [comment]
same issue with iron furnaces, saps the fuel right out

**Comment by BBoldt** [comment]
I don't think its the ic2 config file.

Coal disappears, but coal blocks do not.

What other machines is this happening in?

**Comment by BBoldt** [comment]
It actually seems to be *only* the coal item that disappears in the ic2 generator, other burnable items seem to work fine and not disappear.

**Comment by Pandoras-end-network** [comment]
I tried adding cobblestone into a electric and iron furnace, and from both the cobble disappears. So its not just the generator.

**Comment by BBoldt** [comment]
Seems like it's the right click crop harvest from recently added vtweaks... Check out this issue:

https://github.com/TinyModularThings/IC2Classic/issues/202

**Comment by BBoldt** [comment]
As a temp fix, set right click harvest crops to false in the vtweaks.cfg

**Comment by Pandoras-end-network** [comment]
Amazing, this will keep the players happy untill you find a real fix. Thank you

**Comment by BBoldt** [comment]
```# Allows for right-click-to-harvest on nearly any (including mod) crop. No seeds will be dropped - intended
    B:"Easy Crop Harvesting"=false

**Comment by BBoldt** [comment]
vtweaks removed in 3.19.2
