### ISSUE TITLE
Going to the twilight causes a crash

### ISSUE THREAD

**Issue by Pandoras-end-network** [BBoldt/Unabridged#653]
**Minecraft version:**
1.7.10

**Unabridged or Abridged version:**
Unabridged 3.19.1

**Issue Description:**
Going through a twilight portal, both in singleplayer and on a server causes a crash. Looking at the log it seems like its caused by a combination of vtweaks and Twilight, however just those two mods in an instance do not cause a crash.

After a quick test, setting `B:"Enable Bonemeal Tweak"=false` seems to fix it. But probably more testing is required

**Steps to Reproduce:**
1. Open a twilight portal
2. step through it

**Crash report or log (uploaded to gist.github.com or pastebin.com):**
https://gist.github.com/Pandoras-end-network/2651927b92ee506a03be6dd4d3e4151a

**Comment by maggi373** [comment]
i would prefer an full log, but from what i can see this problem should be fixed with that setting

**Comment by Pandoras-end-network** [comment]
https://gist.github.com/Pandoras-end-network/be13b0e97755bc37347b94c5e59b54e8
This is a direct copy from the server. The line before that is player joining. The line after that is saved crash report

**Comment by maggi373** [comment]
thank you,
[14:52:32] [Server thread/ERROR]: Exception caught during firing event net.minecraftforge.event.entity.player.BonemealEvent@6fda7ff3:
its the bonemeal causing it

**Comment by maggi373** [comment]
why its causing it seems a bit odd, but it might be an conflic between some mods changing the bonemeal

**Comment by Pandoras-end-network** [comment]
It was triggered right after a player entered the twilight, and now it triggers the instance that player joins again. So does that mean something in the twilight triggers that effect?

**Comment by maggi373** [comment]
yes, BlockTFUberousSoil apperently but it seems that there are an weird interaction with vtweaks and twilight using the bonemeal, and by disabling vtweaks setting you mentioned fixes this

**Comment by BBoldt** [comment]
vtweaks removed in 3.19.2
