### ISSUE TITLE
The Extra Utilities Deep Dark and Last Millenium Portals Don't Work

### ISSUE THREAD

**Issue by EmoBubbleGum** [BBoldt/Unabridged#660]
**Minecraft version:** 1.7.10

**Unabridged or Abridged version:** 3.19.2

**Issue Description:** Right clicking the portals doesn't pull you in to their respective dimensions. It simply does nothing. Adding Player API 1.7.10 fixes the issue.

**Steps to Reproduce:** Right click either portal.

**Comment by EmoBubbleGum** [comment]
Fixed if you add Player API for 1.7.10 to the game

**Comment by BBoldt** [comment]
Fixed with 3.19.3
