### ISSUE TITLE
Quartz blocks have smelting recipe conflicts

### ISSUE THREAD

**Issue by EmoBubbleGum** [BBoldt/Unabridged#664]
Minecraft version: 1.7.10

Unabridged or Abridged version: 3.19.1

**Issue Description:** you usually want to get burnt quartz for extra utilities, so this can be rather frustrating, as when it chooses one of the recipes, it sticks with that one until the entire stack is smelted.

**Steps to Reproduce:** smelt quartz blocks

![javaw_exgDireMBo](https://user-images.githubusercontent.com/24841270/105535931-8b441000-5cbd-11eb-84d7-9a0a532d3c08.png)
![javaw_ivy5g4vQF0](https://user-images.githubusercontent.com/24841270/105535937-8e3f0080-5cbd-11eb-93f2-f5bff0a4d4ce.png)

**Comment by BBoldt** [comment]
Fixed with 3.19.3
