### ISSUE TITLE
SDHC alloy needs fire in it's recipe

### ISSUE THREAD

**Issue by BBoldt** [BBoldt/Unabridged#665]
**Minecraft version:**
1.7.10
**Unabridged or Abridged version:**
3.19.2
**Issue Description:**
![image](https://user-images.githubusercontent.com/1463458/105573168-7e044100-5d10-11eb-9d4b-358c78567bdf.png)

**Steps to Reproduce:**

**Crash report or log (uploaded to gist.github.com or pastebin.com):**

**Comment by Pandoras-end-network** [comment]
From what I could gather from old versions and an asian site:
Heavy Duty Plate tier 4
- Compressed Magnesium
- Compressed "SDHC-120" Alloy
- heavy-duty plate tier 3

Heavy duty plate tier 5
- Compressed Cobalt
- Heavy Duty Plate tier 4
- Nickle Plate
- Dolomite Crystal

Compressed "SDHC-120"Alloy
- Compressed Bronze
- Compressed Coal
- Compressed Aluminum

these are the real recipes

**Comment by BBoldt** [comment]
The real issue here is I don't think I'll be able to edit those machine recipes, as galacticraft and galaxy space machines don't have crafttweaker support. 

I wonder if this was a result of me messing with the galacticraft plate oredict in 3.19...

Thanks for the research, I do have some ideas of how to potentially fix this.

**Comment by Pandoras-end-network** [comment]
I ran into the same problem with my quick fix. For now I added shapeless recipes, but atleast this means people on our server can continue, untill a full fix is made.
I also saw te uranium rod needs fire to be crafted, couldnt find the true recipe so far.

**Comment by BBoldt** [comment]
Fixed with 3.19.3
