### ISSUE TITLE
Flim Flam Enchant should be shown in NEI, since there is a recipe (same for many other enchants)

### ISSUE THREAD

**Issue by EmoBubbleGum** [BBoldt/Unabridged#667]
**Minecraft version:**1.7.10

**Unabridged or Abridged version:** 3.19.2

**Issue Description:** Flim Flam is hidden from NEI despite having a recipe. I remember a lot of other enchants having recipes from certain machines as well (I can't remember which ones off the top of my head), so it might be best to unhide some of those too. 

**Steps to Reproduce:**

**Crash report or log (uploaded to gist.github.com or pastebin.com):**

**Comment by BBoldt** [comment]
moved to #668
